#!/usr/bin/env bash
SRC="src/index.ts"

echo "=== VOID DataNet priority landing v1 proof ==="

grep -Fq 'VOID_DATANET_PRIORITY_LANDING_V1' "$SRC"
grep -Fq 'APP.get("/public-node/datanet"' "$SRC"
grep -Fq 'DataNet is VOID' "$SRC"
grep -Fq 'Verify DataNet' "$SRC"
grep -Fq 'Earn WC' "$SRC"
grep -Fq 'Fund VOID' "$SRC"
grep -Fq 'Inspect Public Proof' "$SRC"
grep -Fq 'no public mutation' "$SRC"
grep -Fq 'no WC ledger write' "$SRC"
grep -Fq 'no automatic award' "$SRC"
grep -Fq 'not a faucet' "$SRC"
grep -Fq 'operator review required' "$SRC"
grep -Fq 'published-retrieval-wc-candidate-boundary-v1.json' "$SRC"
grep -Fq 'published-retrieval-operator-review-packet-v1.json' "$SRC"
grep -Fq 'published-retrieval-receipt-v1.json' "$SRC"
grep -Fq 'published-dataset-registry-v1.json' "$SRC"
grep -Fq 'human DataNet landing page' "$SRC"

echo "datanet_priority_landing_route_present=true"
echo "funding_visible=true"
echo "wc_review_candidate_boundary_visible=true"
echo "datanet_receipt_path_visible=true"
echo "public_mutation_performed_now=false"
echo "wc_ledger_write_performed_now=false"
echo "money_movement_performed_now=false"
echo "VOID_DATANET_PRIORITY_LANDING_V1_GREEN"
