#!/usr/bin/env bash
SRC="src/index.ts"

echo "=== VOID funding path tighten v1 proof ==="

grep -Fq 'VOID_FUNDING_PATH_TIGHTEN_V1' "$SRC"
grep -Fq 'APP.get("/public-node/funding"' "$SRC"
grep -Fq 'Funding supports VOID development through a guarded USDC → VOID request path' "$SRC"
grep -Fq 'Manual review required. No automatic token delivery. No investment return, yield, or profit is promised.' "$SRC"
grep -Fq 'Open guarded Buy VOID request' "$SRC"
grep -Fq 'Read funding status' "$SRC"
grep -Fq 'no public fulfillment' "$SRC"
grep -Fq 'no wallet send by this page' "$SRC"
grep -Fq 'A request is not payment confirmation, fulfillment, delivery, or an investment contract.' "$SRC"
grep -Fq 'buy_void_fulfillment now: false' "$SRC"
grep -Fq 'wallet send now: false' "$SRC"
grep -Fq 'money movement now: false' "$SRC"
grep -Fq 'investment return claim: false' "$SRC"
grep -Fq 'yield claim: false' "$SRC"
grep -Fq 'profit promise: false' "$SRC"
grep -Fq 'automatic token delivery: false' "$SRC"
grep -Fq 'human funding path landing page' "$SRC"
grep -Fq 'href="/public-node/funding">Fund VOID' "$SRC"
grep -Fq 'Open funding path' "$SRC"

echo "funding_path_landing_route_present=true"
echo "homepage_fund_void_points_to_public_funding=true"
echo "buy_void_request_flow_still_linked=true"
echo "funding_status_still_linked=true"
echo "manual_review_required_visible=true"
echo "automatic_token_delivery_promised=false"
echo "investment_return_claimed=false"
echo "buy_void_fulfillment_performed_now=false"
echo "wallet_send_performed_now=false"
echo "money_movement_performed_now=false"
echo "VOID_FUNDING_PATH_TIGHTEN_V1_GREEN"
