#!/usr/bin/env bash
set -euo pipefail

REPO="${VOID_NODE_REPO:-$HOME/dev/void-node}"
GATEWAY="$REPO/ops/public/void-public-app-composition-gateway-v1.mjs"

test -f "$GATEWAY"

export VOID_COMPOSITION_HOST="${VOID_COMPOSITION_HOST:-127.0.0.1}"
export VOID_COMPOSITION_PORT="${VOID_COMPOSITION_PORT:-8082}"
export VOID_PUBLIC_GATEWAY_UPSTREAM="${VOID_PUBLIC_GATEWAY_UPSTREAM:-http://127.0.0.1:8080}"
export VOID_NODE_UPSTREAM="${VOID_NODE_UPSTREAM:-http://127.0.0.1:4100}"
export VOID_PUBLIC_EXPECTED_PEERS="${VOID_PUBLIC_EXPECTED_PEERS:-2}"
export VOID_PUBLIC_NODE_LABEL="${VOID_PUBLIC_NODE_LABEL:-Alienware public seed}"
export VOID_PUBLIC_NETWORK_NAME="${VOID_PUBLIC_NETWORK_NAME:-Mainnet-0}"
export VOID_TXROOT_QUARANTINED="${VOID_TXROOT_QUARANTINED:-1}"

exec /usr/bin/node "$GATEWAY"
