#!/usr/bin/env bash
set -euo pipefail
umask 077

REPO="${VOID_NODE_REPO:-$HOME/dev/void-node}"
RECEIVER="$REPO/ops/public/void-operator-webhook-receiver-v1.mjs"

test -f "$RECEIVER"

export VOID_OPERATOR_WEBHOOK_RECEIVER_HOST="${VOID_OPERATOR_WEBHOOK_RECEIVER_HOST:-127.0.0.1}"
export VOID_OPERATOR_WEBHOOK_RECEIVER_PORT="${VOID_OPERATOR_WEBHOOK_RECEIVER_PORT:-4186}"
export VOID_OPERATOR_WEBHOOK_RECEIVER_TOKEN_FILE="${VOID_OPERATOR_WEBHOOK_RECEIVER_TOKEN_FILE:-$HOME/.config/void/credentials/operator-webhook-token-v1}"
export VOID_OPERATOR_WEBHOOK_RECEIVER_STATE_DIR="${VOID_OPERATOR_WEBHOOK_RECEIVER_STATE_DIR:-$HOME/.local/state/void-operator-webhook-receiver-v1}"
export VOID_OPERATOR_WEBHOOK_RECEIVER_HEALTH_OUTPUT="${VOID_OPERATOR_WEBHOOK_RECEIVER_HEALTH_OUTPUT:-$HOME/void-precision-smoke/void-operator-webhook-receiver-health-v1.json}"
export VOID_OPERATOR_WEBHOOK_RECEIVER_MAX_BODY_BYTES="${VOID_OPERATOR_WEBHOOK_RECEIVER_MAX_BODY_BYTES:-65536}"
export VOID_OPERATOR_WEBHOOK_RECEIVER_REQUEST_TIMEOUT_MS="${VOID_OPERATOR_WEBHOOK_RECEIVER_REQUEST_TIMEOUT_MS:-15000}"

exec /usr/bin/node "$RECEIVER"
