#!/usr/bin/env bash
SRC="src/index.ts"

echo "=== VOID WC review path landing v1 proof ==="

grep -Fq 'VOID_WC_REVIEW_PATH_LANDING_V1' "$SRC"
grep -Fq 'APP.get("/public-node/wc"' "$SRC"
grep -Fq 'Work Credits track verified useful contribution' "$SRC"
grep -Fq 'not a reward faucet' "$SRC"
grep -Fq 'not native VOID' "$SRC"
grep -Fq 'not automatic money movement' "$SRC"
grep -Fq 'Open participant console' "$SRC"
grep -Fq 'Verify DataNet' "$SRC"
grep -Fq 'Inspect WC candidate proof' "$SRC"
grep -Fq 'operator decision required' "$SRC"
grep -Fq 'no automatic award' "$SRC"
grep -Fq 'no WC ledger write' "$SRC"
grep -Fq 'VOID remains native currency' "$SRC"
grep -Fq 'reward faucet: false' "$SRC"
grep -Fq 'WC to VOID swap now: false' "$SRC"
grep -Fq 'money movement now: false' "$SRC"
grep -Fq 'first-external-tester-wc-candidate.json' "$SRC"
grep -Fq 'first-external-tester-wc-review-checklist.json' "$SRC"
grep -Fq 'first-external-tester-wc-operator-decision-packet.json' "$SRC"
grep -Fq 'skeptic/work-credits-accounting-boundary-v1.json' "$SRC"
grep -Fq 'human Work Credits review path landing page' "$SRC"

echo "wc_review_path_landing_route_present=true"
echo "participant_console_link_visible=true"
echo "datanet_bridge_visible=true"
echo "wc_candidate_boundary_visible=true"
echo "operator_review_required_visible=true"
echo "reward_faucet_claimed=false"
echo "automatic_award_performed_now=false"
echo "wc_ledger_write_performed_now=false"
echo "wc_to_void_swap_performed_now=false"
echo "money_movement_performed_now=false"
echo "VOID_WC_REVIEW_PATH_LANDING_V1_GREEN"
