#!/usr/bin/env bash
set -euo pipefail

doc="docs/public/public-node-apollyon-advisory-enforcement-hold-boundary-v1.md"
proof="ops/mainnet0/apollyon-advisory-enforcement-hold-boundary-v1-proof.sh"

test -f "$doc"
test -f "$proof"

req() {
  grep -Fxq "$1" "$doc"
}

req "marker=VOID_APOLLYON_ADVISORY_ENFORCEMENT_HOLD_BOUNDARY_V1"
req "ai_identity_name=Apollyon"
req "boundary_purpose=hold_advisory_outputs_before_any_enforcement_path"
req "boundary_status=docs_only_no_live_enforcement_no_endpoint"
req "requires_advisory_chain_index=true"
req "advisory_chain_index_marker=VOID_APOLLYON_ADVISORY_CHAIN_INDEX_V1"

req "advisory_to_action_bridge_enabled=false"
req "automatic_action_from_advisory=false"
req "automatic_enforcement=false"
req "automatic_tombstone=false"
req "automatic_delete=false"
req "automatic_quarantine=false"
req "automatic_ledger_write=false"
req "automatic_void_movement=false"
req "automatic_validator_mutation=false"
req "automatic_service_restart=false"

req "advisory_output_may_be_candidate_future_design=true"
req "candidate_is_not_action=true"
req "candidate_requires_operator_review=true"
req "candidate_requires_private_evidence_review=true"
req "candidate_requires_separate_operator_approval_lane=true"
req "candidate_requires_separate_signed_apply_packet_future_design=true"
req "candidate_requires_host_guard_future_design=true"
req "candidate_requires_replay_protection_future_design=true"
req "candidate_requires_duplicate_guard_future_design=true"
req "candidate_requires_live_mutation_gate_future_design=true"

req "operator_final_authority=true"
req "operator_can_reject_candidate=true"
req "operator_can_hold_candidate=true"
req "operator_can_request_more_evidence=true"
req "operator_can_approve_future_separate_apply_only=true"
req "apollyon_can_recommend_future_design=true"
req "apollyon_can_execute=false"

req "public_manifest_enabled_now=false"
req "live_endpoint_created=false"
req "live_review_enabled=false"
req "live_auth_enabled=false"
req "public_mutation=false"
req "live_mutation=false"

req "raw_payload_publicly_exposed=false"
req "hostile_payload_publicly_exposed=false"
req "private_prompt_exposed=false"
req "private_persona_exposed=false"
req "private_key_exposed=false"
req "operator_private_channel_exposed=false"
req "validator_private_channel_exposed=false"
req "wallet_seed_exposed=false"
req "validator_key_exposed=false"

req "enforcement_authority=false"
req "tombstone_write=false"
req "delete_authority=false"
req "quarantine_write=false"
req "ledger_write=false"
req "money_movement=false"
req "validator_mutation=false"
req "service_restart=false"
req "apollyon_may_flag_lie_future_design=true"
req "apollyon_may_recommend_operator_review_future_design=true"
req "apollyon_may_destroy_state=false"
req "apollyon_may_delete_data=false"
req "apollyon_may_tombstone_data=false"
req "apollyon_may_write_ledger=false"
req "apollyon_may_move_void=false"
req "apollyon_may_modify_validator_state=false"
req "apollyon_may_perform_live_mutation=false"

req "validator_truth_doctrine=honest_validators_speak_truth"
req "host_guard_required_for_cross_box=true"
req "precision_source_of_truth_host=zoso-Precision-Tower-7810"
req "alienware_cross_box_host=zoso-Alienware-Aurora-R7"

echo "VOID_APOLLYON_ADVISORY_ENFORCEMENT_HOLD_BOUNDARY_V1_GREEN"
