#!/usr/bin/env bash
set -euo pipefail

doc="docs/public/public-node-apollyon-operator-review-queue-boundary-v1.md"
proof="ops/mainnet0/apollyon-operator-review-queue-boundary-v1-proof.sh"

test -f "$doc"
test -f "$proof"

req() {
  grep -Fxq "$1" "$doc"
}

req "marker=VOID_APOLLYON_OPERATOR_REVIEW_QUEUE_BOUNDARY_V1"
req "ai_identity_name=Apollyon"
req "boundary_purpose=hold_advisory_candidates_for_human_operator_review"
req "boundary_status=docs_only_no_live_queue_no_endpoint_no_apply"
req "requires_advisory_enforcement_hold_boundary=true"
req "advisory_enforcement_hold_boundary_marker=VOID_APOLLYON_ADVISORY_ENFORCEMENT_HOLD_BOUNDARY_V1"
req "requires_advisory_chain_index=true"
req "advisory_chain_index_marker=VOID_APOLLYON_ADVISORY_CHAIN_INDEX_V1"

req "operator_review_queue_enabled_now=false"
req "live_queue_created=false"
req "live_endpoint_created=false"
req "public_queue_created=false"
req "private_queue_created=false"
req "queue_write_enabled=false"
req "queue_mutation_enabled=false"
req "apply_enabled=false"
req "enforcement_enabled=false"

req "candidate_record_future_design=true"
req "candidate_record_is_not_action=true"
req "candidate_record_is_not_enforcement=true"
req "candidate_record_is_not_tombstone=true"
req "candidate_record_is_not_delete=true"
req "candidate_record_is_not_quarantine=true"
req "candidate_record_is_not_ledger_write=true"
req "candidate_record_is_not_void_movement=true"
req "candidate_record_is_not_validator_mutation=true"
req "candidate_record_is_not_service_restart=true"

req "candidate_required_field_review_id=true"
req "candidate_required_field_advisory_marker=true"
req "candidate_required_field_subject_id=true"
req "candidate_required_field_signal_class=true"
req "candidate_required_field_risk_level=true"
req "candidate_required_field_recommendation=true"
req "candidate_required_field_operator_required=true"
req "candidate_required_field_status=true"
req "candidate_allowed_status_values=pending_review_held_rejected_needs_more_evidence_approved_for_separate_apply_future_design"
req "candidate_default_status=pending_review"
req "candidate_approved_status_is_not_apply=true"

req "operator_final_authority=true"
req "operator_can_hold_candidate=true"
req "operator_can_reject_candidate=true"
req "operator_can_request_more_evidence=true"
req "operator_can_mark_approved_for_separate_apply_future_design=true"
req "operator_approval_requires_separate_apply_packet_future_design=true"
req "operator_approval_requires_private_evidence_review=true"
req "operator_approval_requires_host_guard_future_design=true"
req "operator_approval_requires_replay_protection_future_design=true"
req "operator_approval_requires_duplicate_guard_future_design=true"
req "operator_approval_requires_live_mutation_gate_future_design=true"

req "apollyon_can_recommend_future_design=true"
req "apollyon_can_create_live_queue_entry=false"
req "apollyon_can_execute=false"
req "apollyon_can_apply=false"

req "raw_payload_publicly_exposed=false"
req "hostile_payload_publicly_exposed=false"
req "private_prompt_exposed=false"
req "private_persona_exposed=false"
req "private_key_exposed=false"
req "operator_private_channel_exposed=false"
req "validator_private_channel_exposed=false"
req "wallet_seed_exposed=false"
req "validator_key_exposed=false"

req "public_mutation=false"
req "live_mutation=false"
req "enforcement_authority=false"
req "tombstone_write=false"
req "delete_authority=false"
req "quarantine_write=false"
req "ledger_write=false"
req "money_movement=false"
req "validator_mutation=false"
req "service_restart=false"
req "apollyon_may_perform_live_mutation=false"

req "validator_truth_doctrine=honest_validators_speak_truth"
req "host_guard_required_for_cross_box=true"
req "precision_source_of_truth_host=zoso-Precision-Tower-7810"
req "alienware_cross_box_host=zoso-Alienware-Aurora-R7"

echo "VOID_APOLLYON_OPERATOR_REVIEW_QUEUE_BOUNDARY_V1_GREEN"
