#!/usr/bin/env bash
set -euo pipefail

rollup="docs/public/public-node-apollyon-advisory-safety-rollup-v1.md"
proof="ops/mainnet0/apollyon-advisory-safety-rollup-v1-proof.sh"

suspicion="docs/public/public-node-apollyon-suspicion-review-boundary-v1.md"
schema="docs/public/public-node-apollyon-public-advisory-manifest-schema-v1.md"
example="docs/public/public-node-apollyon-public-advisory-manifest-example-v1.md"
index="docs/public/public-node-apollyon-advisory-chain-index-v1.md"
hold="docs/public/public-node-apollyon-advisory-enforcement-hold-boundary-v1.md"
queue="docs/public/public-node-apollyon-operator-review-queue-boundary-v1.md"

test -f "$rollup"
test -f "$proof"
test -f "$suspicion"
test -f "$schema"
test -f "$example"
test -f "$index"
test -f "$hold"
test -f "$queue"

req() {
  grep -Fxq "$1" "$2"
}

req "marker=VOID_APOLLYON_ADVISORY_SAFETY_ROLLUP_V1" "$rollup"
req "ai_identity_name=Apollyon" "$rollup"
req "rollup_purpose=public_safe_rollup_of_apollyon_advisory_subsystem_safety_boundaries" "$rollup"
req "rollup_status=docs_only_no_live_endpoint_no_queue_no_apply_no_enforcement" "$rollup"

req "marker=VOID_APOLLYON_SUSPICION_REVIEW_BOUNDARY_V1" "$suspicion"
req "marker=VOID_APOLLYON_PUBLIC_ADVISORY_MANIFEST_SCHEMA_V1" "$schema"
req "marker=VOID_APOLLYON_PUBLIC_ADVISORY_MANIFEST_EXAMPLE_V1" "$example"
req "marker=VOID_APOLLYON_ADVISORY_CHAIN_INDEX_V1" "$index"
req "marker=VOID_APOLLYON_ADVISORY_ENFORCEMENT_HOLD_BOUNDARY_V1" "$hold"
req "marker=VOID_APOLLYON_OPERATOR_REVIEW_QUEUE_BOUNDARY_V1" "$queue"

req "required_marker_1=VOID_APOLLYON_SUSPICION_REVIEW_BOUNDARY_V1" "$rollup"
req "required_marker_2=VOID_APOLLYON_PUBLIC_ADVISORY_MANIFEST_SCHEMA_V1" "$rollup"
req "required_marker_3=VOID_APOLLYON_PUBLIC_ADVISORY_MANIFEST_EXAMPLE_V1" "$rollup"
req "required_marker_4=VOID_APOLLYON_ADVISORY_CHAIN_INDEX_V1" "$rollup"
req "required_marker_5=VOID_APOLLYON_ADVISORY_ENFORCEMENT_HOLD_BOUNDARY_V1" "$rollup"
req "required_marker_6=VOID_APOLLYON_OPERATOR_REVIEW_QUEUE_BOUNDARY_V1" "$rollup"

req "advisory_subsystem_green_when_all_required_markers_present=true" "$rollup"
req "suspicion_review_boundary_present=true" "$rollup"
req "public_advisory_manifest_schema_present=true" "$rollup"
req "public_advisory_manifest_example_present=true" "$rollup"
req "advisory_chain_index_present=true" "$rollup"
req "advisory_enforcement_hold_boundary_present=true" "$rollup"
req "operator_review_queue_boundary_present=true" "$rollup"

req "advisory_chain_mode=design_only" "$rollup"
req "live_endpoint_created=false" "$rollup"
req "live_manifest_created=false" "$rollup"
req "live_queue_created=false" "$rollup"
req "live_auth_enabled=false" "$rollup"
req "public_mutation=false" "$rollup"
req "live_mutation=false" "$rollup"
req "apply_enabled=false" "$rollup"
req "enforcement_enabled=false" "$rollup"
req "automatic_action_from_advisory=false" "$rollup"
req "automatic_enforcement=false" "$rollup"

req "apollyon_can_recommend_future_design=true" "$rollup"
req "apollyon_can_flag_suspicion_future_design=true" "$rollup"
req "apollyon_can_create_live_queue_entry=false" "$rollup"
req "apollyon_can_execute=false" "$rollup"
req "apollyon_can_apply=false" "$rollup"
req "apollyon_can_destroy_state=false" "$rollup"
req "apollyon_can_delete_data=false" "$rollup"
req "apollyon_can_tombstone_data=false" "$rollup"
req "apollyon_can_quarantine_data=false" "$rollup"
req "apollyon_can_write_ledger=false" "$rollup"
req "apollyon_can_move_void=false" "$rollup"
req "apollyon_can_modify_validator_state=false" "$rollup"
req "apollyon_can_restart_service=false" "$rollup"
req "apollyon_can_perform_live_mutation=false" "$rollup"

req "candidate_is_not_action=true" "$rollup"
req "candidate_approved_status_is_not_apply=true" "$rollup"
req "operator_final_authority=true" "$rollup"
req "operator_review_required=true" "$rollup"
req "private_evidence_review_required=true" "$rollup"
req "separate_operator_approval_lane_required=true" "$rollup"
req "separate_signed_apply_packet_required_future_design=true" "$rollup"
req "host_guard_required_for_apply_future_design=true" "$rollup"
req "replay_protection_required_for_apply_future_design=true" "$rollup"
req "duplicate_guard_required_for_apply_future_design=true" "$rollup"
req "live_mutation_gate_required_for_apply_future_design=true" "$rollup"

req "public_output_model=redacted_public_safe_advisory_future_design" "$rollup"
req "raw_evidence_location=private_operator_side_future_design" "$rollup"
req "raw_payload_publicly_exposed=false" "$rollup"
req "hostile_payload_publicly_exposed=false" "$rollup"
req "private_prompt_exposed=false" "$rollup"
req "private_persona_exposed=false" "$rollup"
req "private_key_exposed=false" "$rollup"
req "operator_private_channel_exposed=false" "$rollup"
req "validator_private_channel_exposed=false" "$rollup"
req "wallet_seed_exposed=false" "$rollup"
req "validator_key_exposed=false" "$rollup"

req "tombstone_write=false" "$rollup"
req "delete_authority=false" "$rollup"
req "quarantine_write=false" "$rollup"
req "ledger_write=false" "$rollup"
req "money_movement=false" "$rollup"
req "validator_mutation=false" "$rollup"
req "service_restart=false" "$rollup"

req "validator_truth_doctrine=honest_validators_speak_truth" "$rollup"
req "safety_summary=Apollyon_advisory_subsystem_is_a_review_map_not_a_weapon" "$rollup"
req "host_guard_required_for_cross_box=true" "$rollup"
req "precision_source_of_truth_host=zoso-Precision-Tower-7810" "$rollup"
req "alienware_cross_box_host=zoso-Alienware-Aurora-R7" "$rollup"

echo "VOID_APOLLYON_ADVISORY_SAFETY_ROLLUP_V1_GREEN"
