#!/usr/bin/env bash
set -euo pipefail

doc="docs/public/public-node-apollyon-private-revelation-boundary-v1.md"
proof="ops/mainnet0/apollyon-private-revelation-boundary-v1-proof.sh"

test -f "$doc"
test -f "$proof"

req() {
  grep -Fxq "$1" "$doc"
}

req "marker=VOID_APOLLYON_PRIVATE_REVELATION_BOUNDARY_V1"
req "ai_identity_name=Apollyon"
req "boundary_purpose=publicly_known_guardian_with_restricted_communication"
req "public_existence_disclosed=true"
req "public_law_disclosed=true"
req "public_myth_disclosed=true"
req "public_unrestricted_communication=false"
req "public_chat_interface=false"
req "public_prompt_access=false"
req "public_persona_access=false"
req "public_validator_interface_access=false"

req "communication_allowed_to=ZoSo_and_validators_only_future_design"
req "operator_communication_allowed=true"
req "validator_communication_allowed=true"
req "non_validator_public_communication_allowed=false"
req "communication_gate=cryptographic_operator_and_validator_recognition_future_design_only"
req "operator_auth_model=cryptographic_key_recognition_future_design_only"
req "validator_auth_model=cryptographic_validator_identity_recognition_future_design_only"
req "unauthenticated_agent_access=false"
req "hostile_ai_probe_surface_minimized=true"
req "prompt_injection_resistance_goal=true"
req "social_engineering_resistance_goal=true"

req "private_persona_publicly_exposed=false"
req "private_prompts_publicly_exposed=false"
req "private_keys_publicly_exposed=false"
req "private_channels_publicly_exposed=false"
req "validator_channel_publicly_exposed=false"
req "operator_channel_publicly_exposed=false"
req "secret_exposure=false"

req "apollyon_may_disclose_boundary=true"
req "apollyon_may_disclose_public_law=true"
req "apollyon_may_disclose_private_prompt=false"
req "apollyon_may_disclose_private_persona=false"
req "apollyon_may_disclose_validator_channel=false"
req "apollyon_may_disclose_operator_channel=false"
req "apollyon_may_execute_autonomously=false"
req "apollyon_may_override_operator=false"
req "apollyon_may_write_ledger=false"
req "apollyon_may_move_void=false"
req "apollyon_may_modify_validator_state=false"
req "apollyon_may_perform_live_mutation=false"

req "operator_final_authority=true"
req "validator_truth_doctrine=honest_validators_speak_truth"
req "kill_switch_scope=ai_layer_only_not_void_network"
req "public_mutation=false"
req "ledger_write=false"
req "money_movement=false"
req "validator_mutation=false"
req "host_guard_required_for_cross_box=true"
req "precision_source_of_truth_host=zoso-Precision-Tower-7810"
req "alienware_cross_box_host=zoso-Alienware-Aurora-R7"

echo "VOID_APOLLYON_PRIVATE_REVELATION_BOUNDARY_V1_GREEN"
