#!/usr/bin/env bash
set -euo pipefail

doc="docs/public/public-node-apollyon-public-advisory-manifest-schema-v1.md"
proof="ops/mainnet0/apollyon-public-advisory-manifest-schema-v1-proof.sh"

test -f "$doc"
test -f "$proof"

req() {
  grep -Fxq "$1" "$doc"
}

req "marker=VOID_APOLLYON_PUBLIC_ADVISORY_MANIFEST_SCHEMA_V1"
req "ai_identity_name=Apollyon"
req "schema_purpose=future_public_safe_redacted_advisory_manifest_for_suspicion_review"
req "schema_status=design_only_no_live_manifest_no_endpoint"
req "requires_suspicion_review_boundary=true"
req "suspicion_review_boundary_marker=VOID_APOLLYON_SUSPICION_REVIEW_BOUNDARY_V1"

req "manifest_enabled_now=false"
req "live_endpoint_created=false"
req "live_review_enabled=false"
req "live_auth_enabled=false"
req "public_mutation=false"
req "automated_enforcement=false"

req "manifest_type=redacted_public_advisory_future_design_only"
req "manifest_format=json_future_design_only"
req "manifest_audience=human_operators_external_reviewers_and_read_only_agents"
req "manifest_authority=advisory_only"
req "manifest_not_a_tombstone=true"
req "manifest_not_a_delete_command=true"
req "manifest_not_a_quarantine_command=true"
req "manifest_not_a_ledger_entry=true"
req "manifest_not_validator_state=true"

req "required_field_marker=VOID_APOLLYON_PUBLIC_ADVISORY_MANIFEST_V1"
req "required_field_review_id=true"
req "required_field_subject_id=true"
req "required_field_subject_kind=true"
req "required_field_signal_class=true"
req "required_field_risk_level=true"
req "required_field_signal_summary=true"
req "required_field_recommendation=true"
req "required_field_operator_required=true"
req "required_field_enforcement_performed=false"
req "required_field_raw_payload_included=false"
req "required_field_private_material_included=false"
req "required_field_generated_at=true"

req "allowed_signal_class_values=suspicious_stale_poisoned_unknown_future_design"
req "allowed_risk_level_values=low_medium_high_critical_unknown_future_design"
req "allowed_recommendation_values=observe_review_quarantine_candidate_tombstone_candidate_reject_candidate_unknown_future_design"
req "operator_required_for_any_enforcement=true"
req "operator_final_authority=true"

req "raw_payload_publicly_exposed=false"
req "hostile_payload_publicly_exposed=false"
req "private_prompt_exposed=false"
req "private_persona_exposed=false"
req "private_key_exposed=false"
req "operator_private_channel_exposed=false"
req "validator_private_channel_exposed=false"
req "wallet_seed_exposed=false"
req "validator_key_exposed=false"

req "enforcement_authority=false"
req "tombstone_write=false"
req "delete_authority=false"
req "quarantine_write=false"
req "ledger_write=false"
req "money_movement=false"
req "validator_mutation=false"
req "service_restart=false"
req "apollyon_may_flag_lie_future_design=true"
req "apollyon_may_recommend_operator_review_future_design=true"
req "apollyon_may_destroy_state=false"
req "apollyon_may_delete_data=false"
req "apollyon_may_tombstone_data=false"
req "apollyon_may_write_ledger=false"
req "apollyon_may_move_void=false"
req "apollyon_may_modify_validator_state=false"
req "apollyon_may_perform_live_mutation=false"

req "validator_truth_doctrine=honest_validators_speak_truth"
req "host_guard_required_for_cross_box=true"
req "precision_source_of_truth_host=zoso-Precision-Tower-7810"
req "alienware_cross_box_host=zoso-Alienware-Aurora-R7"

echo "VOID_APOLLYON_PUBLIC_ADVISORY_MANIFEST_SCHEMA_V1_GREEN"
