#!/usr/bin/env bash
set -euo pipefail
set +H

MARKER="VOID_DATANET_CORE_PEER_PIN_CURRENT_STATE_CAPSULE_V1"

head_short="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
head_full="$(git rev-parse HEAD 2>/dev/null || echo unknown)"

echo "=== VOID DataNet Core Peer Pin Current State Capsule v1 ==="
echo "marker=$MARKER"
echo "head=$head_short"
echo "head_full=$head_full"
echo "datanet_core_peer_pin_current_state_capsule_created_now=true"
echo "current_state_capsule_terminal_safe=true"
echo "current_state_capsule_runs_full_proof_chain=false"
echo "current_state_capsule_runs_full_live_rollup=false"
echo "focused_proof_index_head=2ada51df"
echo "focused_proof_index_cross_box_green=true"
echo "focused_proof_index_cross_box_tag=ckpt-datanet-core-peer-pin-focused-proof-index-v1-cross-box-green-20260617-213704"
echo "focused_static_guard_proof_path_indexed_now=true"
echo "full_live_status_rollup_execution_required_for_this_lane_now=false"
echo "focused_static_guard_proof_required_for_this_lane_now=true"
echo "focused_static_guard_proof_accepted_for_this_lane_now=true"
echo "peer_pin_current_decision=continue_hold"
echo "exact_command_reveal_allowed_now=false"
echo "exact_command_revealed_now=false"
echo "exact_command_printed_now=false"
echo "command_string_disclosed=false"
echo "final_execute_allowed_now=false"
echo "terminal_execute_allowed_now=false"
echo "command_executed_now=false"
echo "mirror_executed_now=false"
echo "pin_executed_now=false"
echo "public_mutation=false"
echo "ledger_write=false"
echo "wc_credit_award=false"
echo "current_state_capsule_adds_authority=false"
echo "VOID_DATANET_CORE_PEER_PIN_CURRENT_STATE_CAPSULE_V1_GREEN"
