#!/usr/bin/env bash
set -euo pipefail
set +H

MARKER="VOID_DATANET_CORE_PEER_PIN_HOLD_STATUS_ROLLUP_LIVE_GUARD_PROOF_V1"

doc="docs/public/public-node-datanet-core-peer-pin-hold-status-rollup-live-guard-v1.md"
rollup="ops/mainnet0/public-node-live-status-rollup.sh"

echo "=== VOID DataNet Core Peer Pin Hold Status Rollup Live Guard v1 Focused Proof ==="
echo "marker=$MARKER"
echo "head=$(git rev-parse --short HEAD)"

test -f "$doc"
test -f "$rollup"

bash -n "$rollup"

grep -q 'VOID_DATANET_CORE_PEER_PIN_HOLD_STATUS_ROLLUP_LIVE_GUARD_DOC_V1' "$doc"
grep -q 'datanet_core_peer_pin_hold_status_rollup_live_status_rollup_green=true' "$doc"
grep -q 'peer_pin_hold_status_rollup_decision=continue_hold' "$doc"
grep -q 'peer_pin_hold_status_rollup_adds_authority=false' "$doc"
grep -q 'exact_command_revealed_now=false' "$doc"
grep -q 'exact_command_printed_now=false' "$doc"
grep -q 'command_string_disclosed=false' "$doc"
grep -q 'command_executed_now=false' "$doc"
grep -q 'public_mutation=false' "$doc"
grep -q 'ledger_write=false' "$doc"
grep -q 'wc_credit_award=false' "$doc"

grep -q 'VOID_DATANET_CORE_PEER_PIN_HOLD_STATUS_ROLLUP_LIVE_GUARD_V1' "$rollup"
grep -q 'datanet_core_peer_pin_hold_status_rollup_live_status_rollup_green=true' "$rollup"
grep -q 'peer_pin_hold_status_rollup_decision=continue_hold' "$rollup"
grep -q 'peer_pin_hold_status_rollup_hold_chain_green=true' "$rollup"
grep -q 'peer_pin_hold_status_rollup_final_operator_decision_green=true' "$rollup"
grep -q 'peer_pin_hold_status_rollup_cross_box_green=true' "$rollup"
grep -q 'peer_pin_hold_status_rollup_adds_authority=false' "$rollup"
grep -q 'exact_command_reveal_allowed_now=false' "$rollup"
grep -q 'exact_command_revealed_now=false' "$rollup"
grep -q 'exact_command_printed_now=false' "$rollup"
grep -q 'command_string_disclosed=false' "$rollup"
grep -q 'final_execute_allowed_now=false' "$rollup"
grep -q 'terminal_execute_allowed_now=false' "$rollup"
grep -q 'command_executed_now=false' "$rollup"
grep -q 'mirror_executed_now=false' "$rollup"
grep -q 'pin_executed_now=false' "$rollup"
grep -q 'public_mutation=false' "$rollup"
grep -q 'ledger_write=false' "$rollup"
grep -q 'wc_credit_award=false' "$rollup"
grep -q 'VOID_PUBLIC_NODE_LIVE_STATUS_ROLLUP_V1_GREEN' "$rollup"

echo "datanet_core_peer_pin_hold_status_rollup_live_status_rollup_green=true"
echo "peer_pin_hold_status_rollup_decision=continue_hold"
echo "peer_pin_hold_status_rollup_hold_chain_green=true"
echo "peer_pin_hold_status_rollup_final_operator_decision_green=true"
echo "peer_pin_hold_status_rollup_cross_box_green=true"
echo "peer_pin_hold_status_rollup_adds_authority=false"
echo "exact_command_reveal_allowed_now=false"
echo "exact_command_revealed_now=false"
echo "exact_command_printed_now=false"
echo "command_string_disclosed=false"
echo "final_execute_allowed_now=false"
echo "terminal_execute_allowed_now=false"
echo "command_executed_now=false"
echo "mirror_executed_now=false"
echo "pin_executed_now=false"
echo "public_mutation=false"
echo "ledger_write=false"
echo "wc_credit_award=false"
echo "live_guard_proof_scope=focused_static_guard_no_full_rollup_execution"
echo "VOID_DATANET_CORE_PEER_PIN_HOLD_STATUS_ROLLUP_LIVE_GUARD_PROOF_V1_GREEN"
