#!/usr/bin/env bash
set -euo pipefail

SERVICE="${SERVICE:-void-node-live.service}"
DROPIN_DIR="${HOME}/.config/systemd/user/${SERVICE}.d"
DROPIN="${DROPIN_DIR}/20-hot-runtime-quarantine.conf"

mkdir -p "$DROPIN_DIR"

cat > "$DROPIN" <<'CONF'
[Service]
Environment=VOID_QUARANTINE_HOT_RUNTIME=1
Environment=VOID_DISABLE_WRAPPER_STORM=1
Environment=VOID_DISABLE_TERMINAL_SAVEBLOCK=1
Environment=VOID_DISABLE_TERMINAL_SAVEBLOCK_V2=1
Environment=VOID_DISABLE_TXROOT_CORE_BUCKET=1
Environment=VOID_DISABLE_TXROOT_HEADER_NOOP=1
Environment=VOID_DISABLE_EARLY_WRAPPER_FAMILY=1
Environment=VOID_DISABLE_DEDUPE_TRUTHFIX_FORENSICS=1
Environment=VOID_DISABLE_SAVEBLOCK_TAIL=1
Environment=VOID_DISABLE_FINALIZE_WAL_COMMIT=1
Environment=VOID_TXROOT_OBSERVER_DISABLE=1
Environment=VOID_TXROOT_FORENSICS_STICKY_DISABLE=1
Environment=VOID_DISABLE_DRIFT=1
Environment=VOID_DRIFT_DISABLE=1
CONF

systemctl --user daemon-reload

echo "service=${SERVICE}"
echo "dropin=${DROPIN}"
systemctl --user cat "$SERVICE" | grep -E 'VOID_QUARANTINE_HOT_RUNTIME|VOID_DISABLE_WRAPPER_STORM|VOID_DISABLE_SAVEBLOCK_TAIL' >/dev/null

echo "VOID_PUBLIC_NODE_LIVE_RUNTIME_QUARANTINE_INSTALL_V1_GREEN"
