#!/usr/bin/env bash
set -euo pipefail

SRC="src/index.ts"
DOC="docs/public/public-node-operator-ledger-write-runbook-manual-live-write-execute-v1.md"

ROUTE="/public-node/operator-ledger-write-runbook-manual-live-write-execute-v1.json"
GREEN_MARKER="VOID_PUBLIC_NODE_OPERATOR_LEDGER_WRITE_RUNBOOK_MANUAL_LIVE_WRITE_EXECUTE_PROOF_V1_GREEN"

grep -Fq "VOID_PUBLIC_NODE_OPERATOR_LEDGER_WRITE_RUNBOOK_MANUAL_LIVE_WRITE_EXECUTE_V1" "$SRC"
grep -Fq "VOID_PUBLIC_NODE_OPERATOR_LEDGER_WRITE_RUNBOOK_MANUAL_LIVE_WRITE_EXECUTE_ROUTE_V1" "$SRC"
grep -Fq "VOID_PUBLIC_NODE_OPERATOR_LEDGER_WRITE_RUNBOOK_MANUAL_LIVE_WRITE_EXECUTE_UI_V1" "$SRC"
grep -Fq "$ROUTE" "$SRC"

test -f "$DOC"
grep -Fq "VOID_PUBLIC_NODE_OPERATOR_LEDGER_WRITE_RUNBOOK_MANUAL_LIVE_WRITE_EXECUTE_DOC_V1" "$DOC"
grep -Fq "$ROUTE" "$DOC"

grep -Fq "manual_live_write_execute_packet_reviewed: true" "$SRC"
grep -Fq "manual_terminal_execution_required: true" "$SRC"
grep -Fq "exact_operator_execute_command_required: true" "$SRC"
grep -Fq "exact_operator_execute_command_present_now: false" "$SRC"
grep -Fq "execution_disabled_until_exact_operator_command: true" "$SRC"
grep -Fq "idempotency_key_present_now: false" "$SRC"
grep -Fq "public_route_can_never_execute_write: true" "$SRC"
grep -Fq "ready_for_credit_award: false" "$SRC"
grep -Fq "final_live_write_unlock: false" "$SRC"
grep -Fq "manual_live_write_execute_requested_now: false" "$SRC"
grep -Fq "live_runtime_write: false" "$SRC"
grep -Fq "ledger_write_allowed_now: false" "$SRC"
grep -Fq "wc_ledger_write: false" "$SRC"
grep -Fq "wc_ledger_mutated_now: false" "$SRC"
grep -Fq "wc_credit_award: false" "$SRC"
grep -Fq "wc_credit_delta_now: 0" "$SRC"
grep -Fq "automatic_ledger_write_allowed: false" "$SRC"
grep -Fq 'next_gate: "operator_ledger_write_runbook_exact_operator_execute_command_v1"' "$SRC"

echo "VOID_PUBLIC_NODE_OPERATOR_LEDGER_WRITE_RUNBOOK_MANUAL_LIVE_WRITE_EXECUTE_PROOF_V1"
echo "operator_ledger_write_runbook_manual_live_write_execute_packet_reviewed=true"
echo "operator_ledger_write_runbook_manual_live_write_execute_packet_only=true"
echo "operator_ledger_write_runbook_manual_live_write_execute_state=manual_live_write_execute_packet_no_live_write"
echo "operator_ledger_write_runbook_manual_live_write_execute_delta=1"
echo "operator_ledger_write_runbook_manual_live_write_execute_delta_unit=WC"
echo "operator_ledger_write_runbook_manual_live_write_execute_exact_operator_execute_command_present_now=false"
echo "operator_ledger_write_runbook_manual_live_write_execute_requested_now=false"
echo "operator_ledger_write_runbook_manual_live_write_execute_live_runtime_write=false"
echo "operator_ledger_write_runbook_manual_live_write_execute_ledger_write_allowed_now=false"
echo "operator_ledger_write_runbook_manual_live_write_execute_wc_ledger_write=false"
echo "operator_ledger_write_runbook_manual_live_write_execute_wc_credit_delta_now=0"
echo "operator_ledger_write_runbook_manual_live_write_execute_next_gate=operator_ledger_write_runbook_exact_operator_execute_command_v1"
echo "$GREEN_MARKER"
