#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

export NODE_OPTIONS="${NODE_OPTIONS:-}"
export DATA_DIR="${DATA_DIR:-data_a}"
export HTTP_PORT="${HTTP_PORT:-4100}"
export HTTP_HOST="${HTTP_HOST:-0.0.0.0}"
export P2P_PORT="${P2P_PORT:-4700}"
export NODE_PRIVKEY_PATH="${NODE_PRIVKEY_PATH:-$HOME/.secrets/nodeA.key}"

export VOID_DISABLE_RUNTIME_HOTPATH_V1="${VOID_DISABLE_RUNTIME_HOTPATH_V1:-1}"
export VOID_DISABLE_RUNTIME_HOTPATH_V2="${VOID_DISABLE_RUNTIME_HOTPATH_V2:-1}"
export VOID_DISABLE_RUNTIME_HOTPATH_V3="${VOID_DISABLE_RUNTIME_HOTPATH_V3:-1}"
export VOID_DISABLE_RUNTIME_HOTPATH_V4="${VOID_DISABLE_RUNTIME_HOTPATH_V4:-1}"
export VOID_DISABLE_BACKGROUND_LOOPS="${VOID_DISABLE_BACKGROUND_LOOPS:-1}"
export VOID_QUARANTINE_HOT_RUNTIME="${VOID_QUARANTINE_HOT_RUNTIME:-1}"
export VOID_DISABLE_EARLY_WRAPPER_FAMILY="${VOID_DISABLE_EARLY_WRAPPER_FAMILY:-1}"
export VOID_DISABLE_POST_LISTEN_PEER_INTERVALS="${VOID_DISABLE_POST_LISTEN_PEER_INTERVALS:-1}"

echo "[public-safe-local] DATA_DIR=$DATA_DIR HTTP_HOST=$HTTP_HOST HTTP_PORT=$HTTP_PORT P2P_PORT=$P2P_PORT"
echo "[public-safe-local] NODE_PRIVKEY_PATH=$NODE_PRIVKEY_PATH"

exec npm exec -- tsx src/index.ts
