#!/usr/bin/env bash
set -euo pipefail

echo "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_EVIDENCE_BUNDLE_V1_PROOF_BEGIN"

src="src/index.ts"
doc="docs/public/public-node-usdc-external-receipt-observation-evidence-bundle-v1.md"
fixture="fixtures/public/usdc-external-receipt-observation-evidence-bundle-v1.json"
validator="ops/mainnet0/usdc-external-receipt-observation-evidence-bundle-v1.py"

need(){ grep -qF "$1" "$2" || { echo "missing=$1 file=$2"; exit 1; }; }
bad(){ if grep -qF "$1" "$2"; then echo "forbidden=$1 file=$2"; exit 1; fi; }

test "$(grep -F 'runtimeApp.get("/public-node/usdc-void-buy-pool/external-receipt-observation-evidence-bundle-v1.json",' "$src" | wc -l)" = "1"
test "$(grep -F 'runtimeApp.get("/public-node/usdc-void-buy-pool/external-receipt-observation-evidence-bundle-v1",' "$src" | wc -l)" = "1"

python3 "$validator" | grep -qF "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_EVIDENCE_BUNDLE_V1_GREEN"

need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_EVIDENCE_BUNDLE_V1" "$src"
need "/public-node/usdc-void-buy-pool/external-receipt-observation-evidence-bundle-v1.json" "$src"
need "/public-node/usdc-void-buy-pool/external-receipt-observation-evidence-bundle-v1" "$src"
need "evidence_bundle_defined_authority_false" "$src"
need "public_evidence_index_only: true" "$src"
need "VOID_USDC_EXTERNAL_RECEIPT_RPC_READER_USER_AGENT_COMPATIBILITY_REPAIR_V1" "$src"
need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_QUEUE_V1" "$src"
need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_JOB_ENVELOPE_SCHEMA_V1" "$src"
need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_RESULT_ENVELOPE_V1" "$src"
need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_PUBLIC_REVIEWER_CARD_V1" "$src"
need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_PUBLIC_REVIEWER_CARD_RUNTIME_SMOKE_V1" "$src"
need "ckpt-usdc-external-receipt-observation-public-reviewer-card-runtime-smoke-v1-proof-rerun-public-and-alienware-local-green-20260623-122809" "$src"
need "ckpt-usdc-external-receipt-observation-public-reviewer-card-runtime-smoke-v1-cross-box-green-20260623-123336" "$src"
need "ckpt-usdc-external-receipt-observation-public-reviewer-card-html-route-repair-v1-local-green-20260623-120803" "$src"
need "ckpt-usdc-external-receipt-observation-public-reviewer-card-runtime-smoke-v1-local-green-20260623-121450" "$src"
need "ckpt-usdc-external-receipt-observation-public-reviewer-card-runtime-smoke-v1-proof-rerun-local-green-20260623-121815" "$src"
need "ckpt-usdc-external-receipt-observation-public-reviewer-card-runtime-smoke-v1-proof-rerun-local-green-20260623-121834" "$src"
need "not_payment_approval: true" "$src"
need "not_finality_verification: true" "$src"
need "not_allocation_ledger_write: true" "$src"
need "not_inventory_reserve: true" "$src"
need "not_automatic_fulfillment: true" "$src"
need "not_void_transfer: true" "$src"
need "operator_review_required: true" "$src"
need "public_mutation_enabled: false" "$src"
need "runtime_queue_enabled: false" "$src"
need "live_fetch_now: false" "$src"
need "finality_verified_now: false" "$src"
need "external_state_root_trust_enabled: false" "$src"
need "real_payment_verified_now: false" "$src"
need "automatic_fulfillment_enabled: false" "$src"
need "private_allocation_ledger_write_enabled: false" "$src"
need "inventory_reserved_now: false" "$src"
need "void_transfer_now: false" "$src"

need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_EVIDENCE_BUNDLE_V1" "$doc"
need "sealed evidence surfaces" "$doc"
need "Reviewer meaning" "$doc"
need "Non-activation statement" "$doc"
need "The bundle does not approve payment" "$doc"
need "The bundle does not verify finality" "$doc"
need "The bundle does not transfer VOID" "$doc"

need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_EVIDENCE_BUNDLE_V1" "$fixture"
need "\"public_evidence_index_only\": true" "$fixture"
need "\"bundle_subject\": \"usdc_external_receipt_observation\"" "$fixture"
need "\"valid_runtime_smoke_tag\"" "$fixture"
need "\"valid_runtime_smoke_cross_box_tag\"" "$fixture"
need "\"invalid_or_superseded_tags\"" "$fixture"
need "\"not_payment_approval\": true" "$fixture"
need "\"not_finality_verification\": true" "$fixture"
need "\"not_void_transfer\": true" "$fixture"
need "\"operator_review_required\": true" "$fixture"

need "REQUIRED_MARKERS" "$validator"
need "AUTHORITY_FALSE_KEYS" "$validator"
need "WARNING_TRUE_KEYS" "$validator"
need "evidence_bundle_required_items_green=true" "$validator"
need "evidence_bundle_invalid_tag_notes_green=true" "$validator"
need "evidence_bundle_authority_false_green=true" "$validator"

bad "public_mutation_enabled: true" "$src"
bad "runtime_queue_enabled: true" "$src"
bad "live_fetch_now: true" "$src"
bad "finality_verified_now: true" "$src"
bad "external_state_root_trust_enabled: true" "$src"
bad "real_payment_verified_now: true" "$src"
bad "automatic_fulfillment_enabled: true" "$src"
bad "private_allocation_ledger_write_enabled: true" "$src"
bad "inventory_reserved_now: true" "$src"
bad "void_transfer_now: true" "$src"

bad '"public_mutation_enabled": true' "$fixture"
bad '"runtime_queue_enabled": true' "$fixture"
bad '"live_fetch_now": true' "$fixture"
bad '"finality_verified_now": true' "$fixture"
bad '"external_state_root_trust_enabled": true' "$fixture"
bad '"real_payment_verified_now": true' "$fixture"
bad '"automatic_fulfillment_enabled": true' "$fixture"
bad '"private_allocation_ledger_write_enabled": true' "$fixture"
bad '"inventory_reserved_now": true' "$fixture"
bad '"void_transfer_now": true' "$fixture"

echo "evidence_bundle_source_green=true"
echo "evidence_bundle_fixture_green=true"
echo "evidence_bundle_route_duplicate_count_green=true"
echo "evidence_bundle_invalid_tag_notes_green=true"
echo "evidence_bundle_authority_false_green=true"
echo "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_EVIDENCE_BUNDLE_V1_GREEN"
