#!/usr/bin/env bash
set -euo pipefail

echo "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_PUBLIC_REVIEWER_CARD_V1_PROOF_BEGIN"

src="src/index.ts"
doc="docs/public/public-node-usdc-external-receipt-observation-public-reviewer-card-v1.md"
fixture="fixtures/public/usdc-external-receipt-observation-public-reviewer-card-v1.json"
validator="ops/mainnet0/usdc-external-receipt-observation-public-reviewer-card-v1.py"

need(){ grep -qF "$1" "$2" || { echo "missing=$1 file=$2"; exit 1; }; }
bad(){ if grep -qF "$1" "$2"; then echo "forbidden=$1 file=$2"; exit 1; fi; }

test "$(grep -F 'runtimeApp.get("/public-node/usdc-void-buy-pool/external-receipt-observation-public-reviewer-card-v1.json"' "$src" | wc -l)" = "1"
test "$(grep -F 'runtimeApp.get("/public-node/usdc-void-buy-pool/external-receipt-observation-public-reviewer-card-v1"' "$src" | wc -l)" = "2"

python3 "$validator" | grep -qF "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_PUBLIC_REVIEWER_CARD_V1_GREEN"

need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_PUBLIC_REVIEWER_CARD_V1" "$src"
need "/public-node/usdc-void-buy-pool/external-receipt-observation-public-reviewer-card-v1.json" "$src"
need "/public-node/usdc-void-buy-pool/external-receipt-observation-public-reviewer-card-v1" "$src"
need "public_reviewer_card_defined_authority_false" "$src"
need "public_explanation_only: true" "$src"
need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_RESULT_ENVELOPE_V1" "$src"
need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_JOB_ENVELOPE_SCHEMA_V1" "$src"
need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_QUEUE_V1" "$src"
need "not_payment_approval: true" "$src"
need "not_finality_verification: true" "$src"
need "not_allocation_ledger_write: true" "$src"
need "not_inventory_reserve: true" "$src"
need "not_automatic_fulfillment: true" "$src"
need "not_void_transfer: true" "$src"
need "operator_review_required: true" "$src"
need "public_mutation_enabled: false" "$src"
need "runtime_queue_enabled: false" "$src"
need "live_fetch_now: false" "$src"
need "finality_verified_now: false" "$src"
need "external_state_root_trust_enabled: false" "$src"
need "real_payment_verified_now: false" "$src"
need "automatic_fulfillment_enabled: false" "$src"
need "private_allocation_ledger_write_enabled: false" "$src"
need "inventory_reserved_now: false" "$src"
need "void_transfer_now: false" "$src"

need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_PUBLIC_REVIEWER_CARD_V1" "$doc"
need "Reviewer meaning" "$doc"
need "Non-activation statement" "$doc"
need "The card is not payment approval" "$doc"
need "The card is not finality verification" "$doc"
need "The card is not VOID transfer" "$doc"

need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_PUBLIC_REVIEWER_CARD_V1" "$fixture"
need "\"public_explanation_only\": true" "$fixture"
need "\"not_payment_approval\": true" "$fixture"
need "\"not_finality_verification\": true" "$fixture"
need "\"not_void_transfer\": true" "$fixture"
need "\"operator_review_required\": true" "$fixture"

need "WARNING_TRUE_KEYS" "$validator"
need "public_explanation_only_green=true" "$validator"
need "reviewer_warnings_green=true" "$validator"
need "public_reviewer_card_authority_false_green=true" "$validator"

bad "public_mutation_enabled: true" "$src"
bad "runtime_queue_enabled: true" "$src"
bad "live_fetch_now: true" "$src"
bad "finality_verified_now: true" "$src"
bad "external_state_root_trust_enabled: true" "$src"
bad "real_payment_verified_now: true" "$src"
bad "automatic_fulfillment_enabled: true" "$src"
bad "private_allocation_ledger_write_enabled: true" "$src"
bad "inventory_reserved_now: true" "$src"
bad "void_transfer_now: true" "$src"

bad '"public_mutation_enabled": true' "$fixture"
bad '"runtime_queue_enabled": true' "$fixture"
bad '"live_fetch_now": true' "$fixture"
bad '"finality_verified_now": true' "$fixture"
bad '"external_state_root_trust_enabled": true' "$fixture"
bad '"real_payment_verified_now": true' "$fixture"
bad '"automatic_fulfillment_enabled": true' "$fixture"
bad '"private_allocation_ledger_write_enabled": true' "$fixture"
bad '"inventory_reserved_now": true' "$fixture"
bad '"void_transfer_now": true' "$fixture"

echo "public_reviewer_card_source_green=true"
echo "public_reviewer_card_fixture_green=true"
echo "public_reviewer_card_route_duplicate_count_green=true"
echo "public_reviewer_card_authority_false_green=true"
echo "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_PUBLIC_REVIEWER_CARD_V1_GREEN"
