#!/usr/bin/env bash
set -euo pipefail

echo "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_JOB_ENVELOPE_SCHEMA_V1_PROOF_BEGIN"

src="src/index.ts"
doc="docs/public/public-node-usdc-external-receipt-observation-job-envelope-schema-v1.md"
fixture="fixtures/public/usdc-external-receipt-observation-job-envelope-schema-v1.json"
validator="ops/mainnet0/usdc-external-receipt-observation-job-envelope-schema-v1.py"

need(){ grep -qF "$1" "$2" || { echo "missing=$1 file=$2"; exit 1; }; }
bad(){ if grep -qF "$1" "$2"; then echo "forbidden=$1 file=$2"; exit 1; fi; }

test "$(grep -F 'runtimeApp.get("/public-node/usdc-void-buy-pool/external-receipt-observation-job-envelope-schema-v1.json"' "$src" | wc -l)" = "1"

python3 "$validator" | grep -qF "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_JOB_ENVELOPE_SCHEMA_V1_GREEN"

need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_JOB_ENVELOPE_SCHEMA_V1" "$src"
need "/public-node/usdc-void-buy-pool/external-receipt-observation-job-envelope-schema-v1.json" "$src"
need "job_envelope_schema_defined_authority_false" "$src"
need "schema_definition_only: true" "$src"
need "parent_queue_marker: \"VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_QUEUE_V1\"" "$src"
need "job_id" "$src"
need "chain_id" "$src"
need "tx_hash" "$src"
need "rpc_endpoint_class" "$src"
need "classification_state" "$src"
need "retry_allowed" "$src"
need "retry_after_seconds" "$src"
need "operator_review_required" "$src"
need "canonical_payment_identity_hint" "$src"
need "public_mutation_enabled: false" "$src"
need "runtime_queue_enabled: false" "$src"
need "live_fetch_now: false" "$src"
need "finality_verified_now: false" "$src"
need "external_state_root_trust_enabled: false" "$src"
need "real_payment_verified_now: false" "$src"
need "automatic_fulfillment_enabled: false" "$src"
need "private_allocation_ledger_write_enabled: false" "$src"
need "inventory_reserved_now: false" "$src"
need "void_transfer_now: false" "$src"

need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_JOB_ENVELOPE_SCHEMA_V1" "$doc"
need "Required envelope fields" "$doc"
need "Allowed rpc_endpoint_class values" "$doc"
need "Allowed classification_state values" "$doc"
need "Non-activation statement" "$doc"

need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_JOB_ENVELOPE_SCHEMA_V1" "$fixture"
need "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_QUEUE_V1" "$fixture"
need "\"schema_definition_only\": true" "$fixture"
need "\"runtime_queue_enabled\": false" "$fixture"
need "\"live_fetch_now\": false" "$fixture"
need "\"authority_flags\"" "$fixture"
need "\"canonical_payment_identity_hint\"" "$fixture"

need "ALLOWED_RPC_ENDPOINT_CLASSES" "$validator"
need "ALLOWED_CLASSIFICATION_STATES" "$validator"
need "AUTHORITY_FALSE_KEYS" "$validator"
need "canonical_payment_identity_hint_green=true" "$validator"
need "job_envelope_authority_false_green=true" "$validator"

bad "public_mutation_enabled: true" "$src"
bad "runtime_queue_enabled: true" "$src"
bad "live_fetch_now: true" "$src"
bad "finality_verified_now: true" "$src"
bad "external_state_root_trust_enabled: true" "$src"
bad "real_payment_verified_now: true" "$src"
bad "automatic_fulfillment_enabled: true" "$src"
bad "private_allocation_ledger_write_enabled: true" "$src"
bad "inventory_reserved_now: true" "$src"
bad "void_transfer_now: true" "$src"

bad '"public_mutation_enabled": true' "$fixture"
bad '"runtime_queue_enabled": true' "$fixture"
bad '"live_fetch_now": true' "$fixture"
bad '"finality_verified_now": true' "$fixture"
bad '"external_state_root_trust_enabled": true' "$fixture"
bad '"real_payment_verified_now": true' "$fixture"
bad '"automatic_fulfillment_enabled": true' "$fixture"
bad '"private_allocation_ledger_write_enabled": true' "$fixture"
bad '"inventory_reserved_now": true' "$fixture"
bad '"void_transfer_now": true' "$fixture"

echo "job_envelope_schema_source_green=true"
echo "job_envelope_schema_fixture_green=true"
echo "job_envelope_schema_route_duplicate_count_green=true"
echo "job_envelope_schema_authority_false_green=true"
echo "VOID_USDC_EXTERNAL_RECEIPT_OBSERVATION_JOB_ENVELOPE_SCHEMA_V1_GREEN"
