set -euo pipefail
echo "VOID_USDC_TO_VOID_EXTERNAL_STATE_RELAY_VERIFICATION_BOUNDARY_V1_PROOF_BEGIN"
src=src/index.ts
doc=docs/public/public-node-usdc-to-void-external-state-relay-verification-boundary-v1.md
need(){ grep -qF "$1" "$2" || { echo "missing=$1 file=$2"; exit 1; }; }
bad(){ if grep -qF "$1" "$src"; then echo "forbidden=$1"; exit 1; fi; }
need "VOID_USDC_TO_VOID_EXTERNAL_STATE_RELAY_VERIFICATION_BOUNDARY_V1" "$src"
need "/public-node/usdc-void-buy-pool/external-state-relay-verification-boundary-v1.json" "$src"
need "external_state_relay_verification_boundary_defined_authority_false" "$src"
need "external_state_relay_boundary_defined: true" "$src"
need "external_state_relay_boundary_green: false" "$src"
need "external_payment_proof_verifier_enabled: false" "$src"
need "external_state_root_trust_enabled: false" "$src"
need "successful_finalized_usdc_transfer_event_or_future_payment_received_intake_event" "$src"
need "receiver_wallet_balance_increased" "$src"
need "pasted_tx_hash" "$src"
need "explorer_trust" "$src"
need "receiver_balance_delta" "$src"
need "manual_vibes" "$src"
need "source_chain" "$src"
need "source_chain_id" "$src"
need "block_number" "$src"
need "block_hash" "$src"
need "transaction_hash" "$src"
need "transaction_index" "$src"
need "receipt_index" "$src"
need "log_index" "$src"
need "token_contract" "$src"
need "from_address" "$src"
need "to_address" "$src"
need "amount" "$src"
need "canonical_payment_identity" "$src"
need "receipt_root_ref" "$src"
need "state_root_ref" "$src"
need "proof_material_ref" "$src"
need "finality_mode" "$src"
need "trust_mode" "$src"
need "operator_attested_root_initial" "$src"
need "multi_rpc_quorum_future" "$src"
need "ethereum_light_client_future" "$src"
need "zk_external_state_proof_future" "$src"
need "base_l2_finality_policy_future" "$src"
need "transaction_succeeded" "$src"
need "token_contract_allowlisted" "$src"
need "receiver_matches_official_receiver" "$src"
need "amount_matches_quote_or_allocation_rules" "$src"
need "transfer_or_payment_event_exists" "$src"
need "canonical_payment_identity_unique" "$src"
need "payment_not_already_used" "$src"
need "inventory_available_before_allocation" "$src"
need "allocation_record_created_before_fulfillment" "$src"
need "automatic_fulfillment_enabled: false" "$src"
need "wallet_fulfillment_enabled: false" "$src"
need "signer_access_enabled: false" "$src"
need "treasury_transfer_authority_enabled: false" "$src"
need "buyer_execution_authorized: false" "$src"
need "public_mutation_enabled: false" "$src"
need "private_allocation_ledger_write_enabled: false" "$src"
need "void_transfer_now: false" "$src"
need "VOID_USDC_TO_VOID_EXTERNAL_STATE_RELAY_VERIFICATION_BOUNDARY_V1" "$doc"
need "without trusting pasted tx hashes" "$doc"
need "This does not enable automatic fulfillment" "$doc"
need "This does not transfer VOID" "$doc"
need "automatic fulfillment must depend on verified external payment proof" "$doc"
need "not pasted tx hash" "$doc"
need "not explorer trust" "$doc"
need "not receiver balance delta" "$doc"
need "not manual vibes" "$doc"
need "successful finalized USDC Transfer event or future PaymentReceived intake event" "$doc"
bad "external_state_relay_boundary_green: true"
bad "external_payment_proof_verifier_enabled: true"
bad "external_state_root_trust_enabled: true"
bad "private_allocation_ledger_write_enabled: true"
bad "void_transfer_now: true"
echo "external_state_relay_boundary_source_green=true"
echo "pasted_tx_hash_rejected=true"
echo "explorer_trust_rejected=true"
echo "receiver_balance_delta_rejected=true"
echo "payment_event_proof_target_defined=true"
echo "trust_modes_defined=true"
echo "verifier_checks_defined=true"
echo "authority_false=true"
echo "VOID_USDC_TO_VOID_EXTERNAL_STATE_RELAY_VERIFICATION_BOUNDARY_V1_GREEN"
