set -euo pipefail
echo "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_V1_PROOF_BEGIN"
src=src/index.ts
doc=docs/public/public-node-usdc-external-payment-proof-pack-v1.md
need(){ grep -qF "$1" "$2" || { echo "missing=$1 file=$2"; exit 1; }; }
bad(){ if grep -qF "$1" "$src"; then echo "forbidden=$1"; exit 1; fi; }
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_V1" "$src"
need "/public-node/usdc-void-buy-pool/external-payment-proof-pack-v1.json" "$src"
need "VOID_USDC_TO_VOID_EXTERNAL_STATE_RELAY_VERIFICATION_BOUNDARY_V1" "$src"
need "external_payment_proof_pack_shape_defined_authority_false" "$src"
need "external_payment_proof_pack_defined: true" "$src"
need "external_payment_proof_pack_green: false" "$src"
need "proof_pack_shape_only: true" "$src"
need "external_payment_proof_pack_verifier_enabled: false" "$src"
need "external_chain_rpc_fetch_enabled: false" "$src"
need "external_state_root_trust_enabled: false" "$src"
need "ethereum_or_base_finality_verified_now: false" "$src"
need "successful_finalized_usdc_transfer_event_or_future_payment_received_intake_event" "$src"
need "pasted_tx_hash" "$src"
need "explorer_trust" "$src"
need "receiver_balance_delta" "$src"
need "manual_vibes" "$src"
need "proof_pack_version" "$src"
need "source_chain" "$src"
need "source_chain_id" "$src"
need "source_network_family" "$src"
need "block_number" "$src"
need "block_hash" "$src"
need "block_timestamp" "$src"
need "transaction_hash" "$src"
need "transaction_index" "$src"
need "receipt_index" "$src"
need "receipt_status" "$src"
need "log_index" "$src"
need "token_contract" "$src"
need "token_decimals" "$src"
need "from_address" "$src"
need "to_address" "$src"
need "official_receiver_ref" "$src"
need "amount_raw" "$src"
need "amount_decimal" "$src"
need "canonical_payment_identity" "$src"
need "payment_event_type" "$src"
need "receipt_root_ref" "$src"
need "state_root_ref" "$src"
need "proof_material_ref" "$src"
need "finality_mode" "$src"
need "trust_mode" "$src"
need "allocation_rule_ref" "$src"
need "duplicate_guard_ref" "$src"
need "inventory_guard_ref" "$src"
need "receipt_status_success" "$src"
need "token_contract_allowlisted" "$src"
need "to_address_matches_official_receiver" "$src"
need "amount_matches_allocation_rule" "$src"
need "payment_event_exists" "$src"
need "canonical_payment_identity_constructed" "$src"
need "canonical_payment_identity_not_previously_used" "$src"
need "inventory_available_before_allocation" "$src"
need "allocation_record_not_created_by_this_pack" "$src"
need "void_not_transferred_by_this_pack" "$src"
need "automatic_fulfillment_enabled: false" "$src"
need "wallet_fulfillment_enabled: false" "$src"
need "private_allocation_ledger_write_enabled: false" "$src"
need "inventory_reserved_now: false" "$src"
need "void_transfer_now: false" "$src"
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_V1" "$doc"
need "Parent boundary: VOID_USDC_TO_VOID_EXTERNAL_STATE_RELAY_VERIFICATION_BOUNDARY_V1" "$doc"
need "This is proof-pack shape only" "$doc"
need "This does not fetch live chain data" "$doc"
need "This does not verify Ethereum or Base finality" "$doc"
need "This does not enable automatic fulfillment" "$doc"
need "This does not write the private allocation ledger" "$doc"
need "This does not reserve inventory" "$doc"
need "This does not transfer VOID" "$doc"
need "successful finalized USDC Transfer event or future PaymentReceived intake event" "$doc"
bad "external_payment_proof_pack_green: true"
bad "external_payment_proof_pack_verifier_enabled: true"
bad "external_chain_rpc_fetch_enabled: true"
bad "external_state_root_trust_enabled: true"
bad "ethereum_or_base_finality_verified_now: true"
bad "automatic_fulfillment_enabled: true"
bad "wallet_fulfillment_enabled: true"
bad "private_allocation_ledger_write_enabled: true"
bad "inventory_reserved_now: true"
bad "void_transfer_now: true"
echo "external_payment_proof_pack_source_green=true"
echo "proof_pack_shape_only_true=true"
echo "weak_evidence_rejected=true"
echo "required_fields_defined=true"
echo "canonical_payment_identity_components_defined=true"
echo "verifier_expectations_defined=true"
echo "no_rpc_no_finality_no_fulfillment_authority=true"
echo "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_V1_GREEN"
