set -euo pipefail
echo "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_EXAMPLE_V1_PROOF_BEGIN"
src=src/index.ts
doc=docs/public/public-node-usdc-external-payment-proof-pack-example-v1.md
fixture=fixtures/public/usdc-external-payment-proof-pack-example-v1.json
need(){ grep -qF "$1" "$2" || { echo "missing=$1 file=$2"; exit 1; }; }
bad(){ if grep -qF "$1" "$2"; then echo "forbidden=$1 file=$2"; exit 1; fi; }
test "$(grep -F "runtimeApp.get(\"/public-node/usdc-void-buy-pool/external-payment-proof-pack-example-v1.json\"" "$src" | wc -l)" = "1"
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_EXAMPLE_V1" "$src"
need "/public-node/usdc-void-buy-pool/external-payment-proof-pack-example-v1.json" "$src"
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_V1" "$src"
need "example_fixture_shape_only_authority_false" "$src"
need "example_fixture_only: true" "$src"
need "live_chain_data: false" "$src"
need "real_payment: false" "$src"
need "proof_verified_now: false" "$src"
need "finality_verified_now: false" "$src"
need "external_state_root_trust_enabled: false" "$src"
need "automatic_fulfillment_enabled: false" "$src"
need "private_allocation_ledger_write_enabled: false" "$src"
need "inventory_reserved_now: false" "$src"
need "void_transfer_now: false" "$src"
need "canonical_payment_identity" "$src"
need "operator_attested_root_initial_example" "$src"
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_EXAMPLE_V1" "$doc"
need "This is example fixture only" "$doc"
need "This is not a real payment" "$doc"
need "This does not fetch live chain data" "$doc"
need "This does not verify finality" "$doc"
need "This does not transfer VOID" "$doc"
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_EXAMPLE_V1" "$fixture"
need "\"example_fixture_only\": true" "$fixture"
need "\"live_chain_data\": false" "$fixture"
need "\"real_payment\": false" "$fixture"
need "\"proof_verified_now\": false" "$fixture"
need "\"finality_verified_now\": false" "$fixture"
need "\"automatic_fulfillment_enabled\": false" "$fixture"
need "\"void_transfer_now\": false" "$fixture"
need "\"canonical_payment_identity\"" "$fixture"
bad "example_fixture_only: false" "$src"
bad "live_chain_data: true" "$src"
bad "real_payment: true" "$src"
bad "proof_verified_now: true" "$src"
bad "finality_verified_now: true" "$src"
bad "external_state_root_trust_enabled: true" "$src"
bad "automatic_fulfillment_enabled: true" "$src"
bad "private_allocation_ledger_write_enabled: true" "$src"
bad "inventory_reserved_now: true" "$src"
bad "void_transfer_now: true" "$src"
echo "example_fixture_source_green=true"
echo "fixture_json_shape_green=true"
echo "route_duplicate_count_green=true"
echo "no_live_chain_no_real_payment_no_fulfillment_authority=true"
echo "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_EXAMPLE_V1_GREEN"
