set -euo pipefail
echo "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_TRANSFER_LOG_PARSER_V1_PROOF_BEGIN"
src=src/index.ts
doc=docs/public/public-node-usdc-external-payment-proof-pack-transfer-log-parser-v1.md
fixture=fixtures/public/usdc-external-payment-proof-pack-transfer-log-parser-example-v1.json
parser=ops/mainnet0/usdc-external-payment-proof-pack-transfer-log-parser-v1.py
need(){ grep -qF "$1" "$2" || { echo "missing=$1 file=$2"; exit 1; }; }
bad(){ if grep -qF "$1" "$2"; then echo "forbidden=$1 file=$2"; exit 1; fi; }
test "$(grep -F "runtimeApp.get(\"/public-node/usdc-void-buy-pool/external-payment-proof-pack-transfer-log-parser-v1.json\"" "$src" | wc -l)" = "1"
python3 "$parser" | grep -qF "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_TRANSFER_LOG_PARSER_V1_GREEN"
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_TRANSFER_LOG_PARSER_V1" "$src"
need "/public-node/usdc-void-buy-pool/external-payment-proof-pack-transfer-log-parser-v1.json" "$src"
need "transfer_log_parser_defined_authority_false" "$src"
need "transfer_log_parser_execution_green: true" "$src"
need "transfer_log_parser_activation_enabled: false" "$src"
need "offline_fixture_only: true" "$src"
need "erc20_transfer_topic0_checked: true" "$src"
need "transfer_log_token_contract_checked: true" "$src"
need "transfer_log_receiver_checked: true" "$src"
need "transfer_log_amount_checked: true" "$src"
need "canonical_payment_identity_checked: true" "$src"
need "live_chain_data: false" "$src"
need "external_chain_rpc_fetch_enabled: false" "$src"
need "real_payment_verified_now: false" "$src"
need "finality_verified_now: false" "$src"
need "automatic_fulfillment_enabled: false" "$src"
need "private_allocation_ledger_write_enabled: false" "$src"
need "inventory_reserved_now: false" "$src"
need "void_transfer_now: false" "$src"
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_TRANSFER_LOG_PARSER_V1" "$doc"
need "ERC-20 Transfer topic0" "$doc"
need "Non-activation statement" "$doc"
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_TRANSFER_LOG_PARSER_EXAMPLE_V1" "$fixture"
need "erc20_transfer_topic0" "$fixture"
need "transfer_log_receiver_matches_official_receiver" "$fixture"
need "transfer_log_amount_matches_payment_amount" "$fixture"
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_TRANSFER_LOG_PARSER_V1_GREEN" "$parser"
need "erc20_transfer_topic0_mismatch" "$parser"
need "transfer_log_token_contract_mismatch" "$parser"
need "transfer_log_to_address_mismatch" "$parser"
need "transfer_log_amount_raw_mismatch" "$parser"
need "canonical_payment_identity_mismatch" "$parser"
bad "transfer_log_parser_activation_enabled: true" "$src"
bad "live_chain_data: true" "$src"
bad "external_chain_rpc_fetch_enabled: true" "$src"
bad "real_payment_verified_now: true" "$src"
bad "finality_verified_now: true" "$src"
bad "automatic_fulfillment_enabled: true" "$src"
bad "private_allocation_ledger_write_enabled: true" "$src"
bad "inventory_reserved_now: true" "$src"
bad "void_transfer_now: true" "$src"
echo "transfer_log_parser_source_green=true"
echo "transfer_log_parser_execution_green=true"
echo "transfer_log_parser_route_duplicate_count_green=true"
echo "transfer_log_parser_authority_false_green=true"
echo "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_TRANSFER_LOG_PARSER_V1_GREEN"
