set -euo pipefail
echo "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_STATIC_VERIFIER_V1_PROOF_BEGIN"
src=src/index.ts
doc=docs/public/public-node-usdc-external-payment-proof-pack-static-verifier-v1.md
verifier=ops/mainnet0/usdc-external-payment-proof-pack-static-verifier-v1.py
fixture=fixtures/public/usdc-external-payment-proof-pack-example-v1.json
need(){ grep -qF "$1" "$2" || { echo "missing=$1 file=$2"; exit 1; }; }
bad(){ if grep -qF "$1" "$2"; then echo "forbidden=$1 file=$2"; exit 1; fi; }
test "$(grep -F "runtimeApp.get(\"/public-node/usdc-void-buy-pool/external-payment-proof-pack-static-verifier-v1.json\"" "$src" | wc -l)" = "1"
python3 "$verifier" | grep -qF "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_STATIC_VERIFIER_V1_GREEN"
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_STATIC_VERIFIER_V1" "$src"
need "/public-node/usdc-void-buy-pool/external-payment-proof-pack-static-verifier-v1.json" "$src"
need "static_verifier_defined_authority_false" "$src"
need "static_verifier_defined: true" "$src"
need "static_verifier_execution_green: true" "$src"
need "static_verifier_activation_enabled: false" "$src"
need "reads_checked_in_fixture_only: true" "$src"
need "live_chain_data: false" "$src"
need "external_chain_rpc_fetch_enabled: false" "$src"
need "real_payment_verified_now: false" "$src"
need "finality_verified_now: false" "$src"
need "external_state_root_trust_enabled: false" "$src"
need "required_root_fields_checked: true" "$src"
need "required_proof_pack_fields_checked: true" "$src"
need "authority_false_fields_checked: true" "$src"
need "canonical_payment_identity_checked: true" "$src"
need "automatic_fulfillment_enabled: false" "$src"
need "private_allocation_ledger_write_enabled: false" "$src"
need "inventory_reserved_now: false" "$src"
need "void_transfer_now: false" "$src"
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_STATIC_VERIFIER_V1" "$doc"
need "This verifier reads only the checked-in example fixture" "$doc"
need "This verifier does not fetch live chain data" "$doc"
need "This verifier does not verify Ethereum or Base finality" "$doc"
need "This verifier does not transfer VOID" "$doc"
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_STATIC_VERIFIER_V1_GREEN" "$verifier"
need "canonical_payment_identity_mismatch" "$verifier"
need "authority_must_remain_false" "$verifier"
need "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_EXAMPLE_V1" "$fixture"
bad "static_verifier_activation_enabled: true" "$src"
bad "live_chain_data: true" "$src"
bad "external_chain_rpc_fetch_enabled: true" "$src"
bad "real_payment_verified_now: true" "$src"
bad "finality_verified_now: true" "$src"
bad "external_state_root_trust_enabled: true" "$src"
bad "automatic_fulfillment_enabled: true" "$src"
bad "private_allocation_ledger_write_enabled: true" "$src"
bad "inventory_reserved_now: true" "$src"
bad "void_transfer_now: true" "$src"
echo "static_verifier_source_green=true"
echo "static_verifier_execution_green=true"
echo "static_verifier_route_duplicate_count_green=true"
echo "static_verifier_authority_false_green=true"
echo "VOID_USDC_EXTERNAL_PAYMENT_PROOF_PACK_STATIC_VERIFIER_V1_GREEN"
