set -euo pipefail
echo "VOID_USDC_TO_VOID_PRESALE_PRIVATE_LEDGER_PATH_NO_LEAK_PREFLIGHT_V1_PROOF_BEGIN"
src=src/index.ts
doc=docs/public/public-node-usdc-to-void-presale-private-ledger-path-no-leak-preflight-v1.md
need(){ grep -qF "$1" "$2" || { echo "missing=$1 file=$2"; exit 1; }; }
bad(){ if grep -qF "$1" "$src"; then echo "forbidden=$1"; exit 1; fi; }
need "VOID_USDC_TO_VOID_PRESALE_PRIVATE_LEDGER_PATH_NO_LEAK_PREFLIGHT_V1" "$src"
need "/public-node/usdc-void-buy-pool/private-ledger-path-no-leak-preflight-v1.json" "$src"
need "private_ledger_path_no_leak_preflight_defined_authority_false" "$src"
need "private_ledger_path_no_leak_preflight_green: false" "$src"
need "private_ledger_path_selected: false" "$src"
need "private_ledger_path_publicly_disclosed: false" "$src"
need "private_allocation_ledger_activation_authorized: false" "$src"
need "private_allocation_ledger_created: false" "$src"
need "private_allocation_ledger_write_enabled: false" "$src"
need "public_route_discloses_private_ledger_path: false" "$src"
need "actual_private_ledger_path_present: false" "$src"
need "private_path_material_present: false" "$src"
need "private_ledger_path_ref" "$src"
need "private_ledger_path_commitment" "$src"
need "private_ledger_path_no_leak_proof_ref" "$src"
need "absolute_filesystem_path" "$src"
need "home_directory_path" "$src"
need "operator_username_path" "$src"
need "private_data_directory" "$src"
need "buyer_delivery_wallet" "$src"
need "raw_payment_receipt_material" "$src"
need "operator_execution_commands" "$src"
need "seed_phrase_key_or_secret" "$src"
need "automatic_fulfillment_enabled: false" "$src"
need "void_transfer_now: false" "$src"
need "VOID_USDC_TO_VOID_PRESALE_PRIVATE_LEDGER_PATH_NO_LEAK_PREFLIGHT_V1" "$doc"
need "does not select the private ledger path" "$doc"
need "does not print the private ledger path" "$doc"
need "does not create a ledger file" "$doc"
need "does not enable writes" "$doc"
need "does not activate the private ledger" "$doc"
need "does not reserve inventory" "$doc"
need "does not fulfill VOID" "$doc"
need "Public route may expose only opaque path references" "$doc"
bad "private_ledger_path_no_leak_preflight_green: true"
bad "private_ledger_path_selected: true"
bad "private_ledger_path_publicly_disclosed: true"
bad "private_allocation_ledger_activation_authorized: true"
bad "private_allocation_ledger_created: true"
bad "private_allocation_ledger_write_enabled: true"
bad "public_route_discloses_private_ledger_path: true"
bad "actual_private_ledger_path_present: true"
bad "private_path_material_present: true"
bad "automatic_fulfillment_enabled: true"
bad "void_transfer_now: true"
echo "private_ledger_path_no_leak_preflight_source_green=true"
echo "path_selected_false=true"
echo "path_publicly_disclosed_false=true"
echo "no_private_path_material_present=true"
echo "ledger_creation_and_write_false=true"
echo "opaque_reference_rules_defined=true"
echo "automatic_fulfillment_still_false=true"
echo "VOID_USDC_TO_VOID_PRESALE_PRIVATE_LEDGER_PATH_NO_LEAK_PREFLIGHT_V1_GREEN"
