[Service]
Environment=VOID_ROLE=proposer
Environment=VOID_SAFEBOOT=0
Environment=PROPOSER_AUTO=0
Environment=VOID_PROPOSER_AUTOSTART=0
Environment=PROPOSER_TICK_MS=2000
Environment=BOOTSTRAP_ADDRS=127.0.0.1:4700,127.0.0.1:4701
