[Service]
Environment=TXROOT_HOOK_DISABLE=1
Environment=TXROOT_CORE_DISABLE=1
Environment=TXROOT_CORE_METRICS_DISABLE=1
Environment=TXROOT_FORENSICS_DISABLE=1
Environment=TXROOT_OBSERVER_DISABLE=1
Environment=TXROOT_HEADER_WRITE_DISABLE=1
