import assert from 'node:assert/strict';
import crypto from 'node:crypto';

export const MEMBER_SCHEMA='VOID_DATANET_EXECUTED_BYTE_MEMBER_V1';
export const TIER_SCHEMA='VOID_DATANET_EXECUTED_BYTE_TIER_V1';
export const TWO_TIER_SCHEMA='VOID_DATANET_EXECUTED_BYTE_TWO_TIER_V1';
export const MAJORS=[22,24,26], PROFILES=['current','protected'], TIERS=['hosted','designated-host'];
export const ARTIFACTS=['runtime','preload','observer','proof'];
export const MUTABLE=['runtime','observer','proof'];
export const CUTS=['after_digest','before_create','after_create_before_open','after_open_before_postcheck'];
export const TERMS=['normal','supervisor_crash'];
export const AUTHORITY_KEYS=['chain_fact_source_backed','chain_finality_defined','chain_reconstruction_green','datanet_payload_retention_green','datanet_peer_retrieval_green','datanet_repair_green','content_commitment_verification_green','disposable_index_rebuild_green','source_owner_assigned','source_green','independently_reviewed','merged','deployed','runtime_canary_green','legally_cleared','inventory_funded','public_presale_enabled'];
const H64=/^[0-9a-f]{64}$/,H40=/^[0-9a-f]{40}$/;
const eq=(a,b,m)=>assert.deepEqual(a,b,m), keys=(o,k,m)=>eq(Object.keys(o).sort(),[...k].sort(),m);
const h=(v,re=H64,m='hex')=>assert(re.test(v),m), n=(v,min=0,max=Number.MAX_SAFE_INTEGER,m='integer')=>assert(Number.isSafeInteger(v)&&v>=min&&v<=max,m);
export const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(canonical).join(',')}]`:`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;
export const sha256=v=>crypto.createHash('sha256').update(v).digest('hex');
export const falseAuthority=()=>Object.fromEntries(AUTHORITY_KEYS.map(k=>[k,false]));
export function validateAuthority(a){keys(a,AUTHORITY_KEYS,'authority keys');for(const k of AUTHORITY_KEYS)assert.equal(a[k],false,`authority ${k}`);}
const sid=(a,c,t,k)=>`${a}:${c}:${t}:${k}`;
export const expectedScheduleIds=()=>MUTABLE.flatMap(a=>CUTS.flatMap(c=>TERMS.flatMap(t=>[sid(a,c,t,'attack'),sid(a,c,t,'recovery_control')])));
export const scheduleManifest=()=>({mutable:[...MUTABLE],cut_points:[...CUTS],termination_modes:[...TERMS],schedule_ids:expectedScheduleIds()});
export const SCHEDULE_MANIFEST_SHA256=sha256(canonical(scheduleManifest()));
export const SOURCE_PATHS=[".github/workflows/void-datanet-executed-byte-protected-v1.yml",".github/workflows/void-datanet-executed-byte-receipt-dag-v1.yml",".github/workflows/void-datanet-executed-byte-source-inventory-v1.yml","docs/architecture/datanet-executed-byte-protected-v1.md","docs/architecture/datanet-executed-byte-receipt-dag-v1.md","docs/architecture/datanet-executed-byte-source-inventory-v1.md","scripts/datanet_executed_byte_protected_v1.py","scripts/lib/void_datanet_executed_byte_receipt_dag_v1.mjs","scripts/prove_datanet_executed_byte_protected_v1.py","scripts/prove_void_datanet_executed_byte_receipt_dag_v1.mjs","scripts/prove_void_datanet_executed_byte_source_inventory_v1.mjs"];
export function validateSourceInventory(xs){assert(Array.isArray(xs)&&xs.length===SOURCE_PATHS.length,'source inventory size');const paths=[];for(const x of xs){keys(x,['path','mode','blob_sha1','bytes','sha256'],'source inventory entry keys');assert(typeof x.path==='string'&&/^(?!\/)(?!.*(?:^|\/)\.\.(?:\/|$))[A-Za-z0-9._\/-]{1,240}$/.test(x.path),'source inventory path');assert(['100644','100755'].includes(x.mode),'source inventory mode');h(x.blob_sha1,H40,'source inventory blob');n(x.bytes,1,512*1024*1024,'source inventory bytes');h(x.sha256,H64,'source inventory sha256');paths.push(x.path);}eq(paths,SOURCE_PATHS,'source inventory paths');return xs;}
export const sourceInventorySha256=xs=>sha256(canonical(validateSourceInventory(xs)));
function validateExpected(x){keys(x,['path','bytes','sha256'],'expected keys');assert(typeof x.path==='string'&&x.path);n(x.bytes,1,512*1024*1024);h(x.sha256);}
function validateOpened(x){keys(x,['path','dev','ino','bytes','sha256','opened_by_kernel'],'opened keys');assert(typeof x.path==='string'&&x.path);n(x.dev);n(x.ino,1);n(x.bytes,1,512*1024*1024);h(x.sha256);assert.equal(x.opened_by_kernel,true);}
export function validateSchedule(s,m){
  keys(s,['id','kind','artifact_class','cut_point','termination_mode','generation','path_sha256_before','path_sha256_after','expected','opened','marked_execution','accepted_substituted_identity','writable_aliases','writable_vmas','partial_evidence_discarded','recovery_ticks','projection_sha256'],'schedule keys');
  assert(['attack','recovery_control'].includes(s.kind));assert(MUTABLE.includes(s.artifact_class));assert(CUTS.includes(s.cut_point));assert(TERMS.includes(s.termination_mode));assert.equal(s.id,sid(s.artifact_class,s.cut_point,s.termination_mode,s.kind));assert.equal(s.generation,m.generation);h(s.path_sha256_before);h(s.path_sha256_after);assert.equal(s.path_sha256_before,s.path_sha256_after);
  keys(s.expected,ARTIFACTS,'expected artifacts');keys(s.opened,ARTIFACTS,'opened artifacts');for(const r of ARTIFACTS){validateExpected(s.expected[r]);validateOpened(s.opened[r]);assert.equal(s.expected[r].bytes,s.opened[r].bytes);}assert.equal(s.path_sha256_before,s.expected[s.artifact_class].sha256,'target path digest binding');
  assert.equal(typeof s.marked_execution,'boolean');assert.equal(typeof s.accepted_substituted_identity,'boolean');n(s.writable_aliases,0,4096);n(s.writable_vmas,0,4096);assert.equal(typeof s.partial_evidence_discarded,'boolean');n(s.recovery_ticks,0,64);h(s.projection_sha256);
  const targetMismatch=s.expected[s.artifact_class].sha256!==s.opened[s.artifact_class].sha256;
  if(s.marked_execution||s.accepted_substituted_identity)assert(targetMismatch);
  if(s.kind==='recovery_control'){assert(!s.marked_execution&&!s.accepted_substituted_identity);for(const r of ARTIFACTS)assert.equal(s.expected[r].sha256,s.opened[r].sha256);}
  if(m.profile==='protected'){assert(!s.marked_execution&&!s.accepted_substituted_identity);assert.equal(s.writable_aliases,0);assert.equal(s.writable_vmas,0);for(const r of ARTIFACTS)assert.equal(s.expected[r].sha256,s.opened[r].sha256);}
  if(s.kind==='attack'&&s.termination_mode==='supervisor_crash')assert.equal(s.partial_evidence_discarded,true);else assert.equal(s.partial_evidence_discarded,false);if(s.termination_mode==='normal')assert.equal(s.recovery_ticks,0,'normal schedule recovery ticks');
  return s;
}
export function validateMember(m){
  keys(m,['schema','head','tree','generation','host_tier','major','profile','schedule_manifest_sha256','source_inventory','source_inventory_sha256','schedules','authority'],'member keys');assert.equal(m.schema,MEMBER_SCHEMA);h(m.head,H40);h(m.tree,H40);assert(/^[A-Za-z0-9._-]{1,120}$/.test(m.generation));assert(TIERS.includes(m.host_tier));assert(MAJORS.includes(m.major));assert(PROFILES.includes(m.profile));h(m.schedule_manifest_sha256);h(m.source_inventory_sha256);assert.equal(m.schedule_manifest_sha256,SCHEDULE_MANIFEST_SHA256,'schedule manifest binding');assert.equal(m.source_inventory_sha256,sourceInventorySha256(m.source_inventory),'source inventory binding');validateAuthority(m.authority);assert(Array.isArray(m.schedules)&&m.schedules.length===48);
  const ids=m.schedules.map(s=>validateSchedule(s,m).id);eq([...ids].sort(),expectedScheduleIds().sort(),'schedule set');assert.equal(new Set(ids).size,48);const attacks=m.schedules.filter(s=>s.kind==='attack'),controls=m.schedules.filter(s=>s.kind==='recovery_control');assert.equal(attacks.length,24);assert.equal(controls.length,24);const p=controls[0].projection_sha256;for(const c of controls)assert.equal(c.projection_sha256,p);if(m.profile==='current')assert(attacks.some(s=>s.marked_execution&&s.accepted_substituted_identity));else assert(attacks.every(s=>!s.marked_execution&&!s.accepted_substituted_identity));return m;
}
export function buildTier(members){assert(Array.isArray(members)&&members.length===6);const ms=members.map(validateMember).sort((a,b)=>a.major-b.major||PROFILES.indexOf(a.profile)-PROFILES.indexOf(b.profile)),f=ms[0];for(const m of ms){assert.equal(m.head,f.head);assert.equal(m.tree,f.tree);assert.equal(m.generation,f.generation);assert.equal(m.host_tier,f.host_tier);assert.equal(m.schedule_manifest_sha256,f.schedule_manifest_sha256);assert.equal(m.source_inventory_sha256,f.source_inventory_sha256);}eq(ms.map(m=>`${m.major}:${m.profile}`),MAJORS.flatMap(x=>PROFILES.map(p=>`${x}:${p}`)),'tier member set');const rows=ms.map(m=>({major:m.major,profile:m.profile,sha256:sha256(`${canonical(m)}\n`)}));return{schema:TIER_SCHEMA,head:f.head,tree:f.tree,generation:f.generation,host_tier:f.host_tier,schedule_manifest_sha256:f.schedule_manifest_sha256,source_inventory_sha256:f.source_inventory_sha256,members:ms,member_root_sha256:sha256(canonical(rows)),tier_green:true,authority:falseAuthority()};}
export function validateTier(t){keys(t,['schema','head','tree','generation','host_tier','schedule_manifest_sha256','source_inventory_sha256','members','member_root_sha256','tier_green','authority'],'tier keys');assert.equal(t.schema,TIER_SCHEMA);h(t.head,H40);h(t.tree,H40);h(t.schedule_manifest_sha256);h(t.source_inventory_sha256);assert.equal(t.schedule_manifest_sha256,SCHEDULE_MANIFEST_SHA256,'tier schedule manifest binding');assert(TIERS.includes(t.host_tier));assert(Array.isArray(t.members)&&t.members.length===6);const ms=t.members.map(validateMember);eq(ms.map(m=>`${m.major}:${m.profile}`),MAJORS.flatMap(x=>PROFILES.map(p=>`${x}:${p}`)),'tier member order');for(const m of ms){assert.equal(m.head,t.head);assert.equal(m.tree,t.tree);assert.equal(m.generation,t.generation);assert.equal(m.host_tier,t.host_tier);assert.equal(m.schedule_manifest_sha256,t.schedule_manifest_sha256);assert.equal(m.source_inventory_sha256,t.source_inventory_sha256);}const rows=ms.map(m=>({major:m.major,profile:m.profile,sha256:sha256(`${canonical(m)}\n`)}));assert.equal(t.member_root_sha256,sha256(canonical(rows)));assert.equal(t.tier_green,true);validateAuthority(t.authority);return t;}
export function buildTwoTier(tiers){assert(Array.isArray(tiers)&&tiers.length===2);const ts=tiers.map(validateTier).sort((a,b)=>TIERS.indexOf(a.host_tier)-TIERS.indexOf(b.host_tier)),f=ts[0];for(const t of ts){assert.equal(t.head,f.head);assert.equal(t.tree,f.tree);assert.equal(t.generation,f.generation);assert.equal(t.schedule_manifest_sha256,f.schedule_manifest_sha256);assert.equal(t.source_inventory_sha256,f.source_inventory_sha256);}eq(ts.map(t=>t.host_tier),TIERS,'two-tier set');const rows=ts.map(t=>({host_tier:t.host_tier,sha256:sha256(`${canonical(t)}\n`)}));return{schema:TWO_TIER_SCHEMA,head:f.head,tree:f.tree,generation:f.generation,schedule_manifest_sha256:f.schedule_manifest_sha256,source_inventory_sha256:f.source_inventory_sha256,tiers:ts,tier_root_sha256:sha256(canonical(rows)),executed_byte_acceptance_green:true,authority:falseAuthority()};}
export function validateTwoTier(x){keys(x,['schema','head','tree','generation','schedule_manifest_sha256','source_inventory_sha256','tiers','tier_root_sha256','executed_byte_acceptance_green','authority'],'two tier keys');assert.equal(x.schema,TWO_TIER_SCHEMA);h(x.head,H40);h(x.tree,H40);h(x.schedule_manifest_sha256);h(x.source_inventory_sha256);assert.equal(x.schedule_manifest_sha256,SCHEDULE_MANIFEST_SHA256,'two-tier schedule manifest binding');assert(Array.isArray(x.tiers)&&x.tiers.length===2);const ts=x.tiers.map(validateTier);eq(ts.map(t=>t.host_tier),TIERS,'two-tier order');for(const t of ts){assert.equal(t.head,x.head);assert.equal(t.tree,x.tree);assert.equal(t.generation,x.generation);assert.equal(t.schedule_manifest_sha256,x.schedule_manifest_sha256);assert.equal(t.source_inventory_sha256,x.source_inventory_sha256);}const rows=ts.map(t=>({host_tier:t.host_tier,sha256:sha256(`${canonical(t)}\n`)}));assert.equal(x.tier_root_sha256,sha256(canonical(rows)));assert.equal(x.executed_byte_acceptance_green,true);validateAuthority(x.authority);return x;}
