// VOID_APOLLYON_OPENROUTER_BROKER_ADMISSION_CAPABILITY_V1
// Local exact-work admission evidence only. NO provider network, credential, retry,
// resend, wallet, chain, validator, repository, or service-control authority exists here.
import { createHash } from 'node:crypto';
import { constants as FS } from 'node:fs';
import { open as fsOpen, lstat as fsLstat } from 'node:fs/promises';
import { publishReceiptExact } from './apollyon_secret_sanitization_constitutional_admission_v1.mjs';
const MODULE_ID='VOID_APOLLYON_OPENROUTER_BROKER_ADMISSION_CAPABILITY_V1';
const MARKER='VOID_APOLLYON_OPENROUTER_BROKER_ADMISSION_CAPABILITY_V1';
const ID_MARKER='VOID_APOLLYON_OPENROUTER_BROKER_ADMISSION_CAPABILITY_ID_V1';
const HEX64=/^[0-9a-f]{64}$/, OP=/^apollyon_op_v1:[0-9a-f]{64}$/, TRIAL=/^voidat1_[0-9a-f]{64}$/, ADMISSION=/^voidaa1_[0-9a-f]{64}$/, CAP=/^voidobac1_[0-9a-f]{64}$/;
const MODEL=/^[a-z0-9._-]+\/[A-Za-z0-9._:-]+$/, CANON=/^[a-z0-9._~-]+\/[A-Za-z0-9._~:-]+$/, MAX_BYTES=64*1024;
function fail(m){throw new Error(`${MODULE_ID}: ${m}`)}
function plain(v){if(v===null||typeof v!=='object'||Array.isArray(v))return false;const p=Object.getPrototypeOf(v);return p===Object.prototype||p===null}
function canonical(v){if(v===null||typeof v==='boolean')return JSON.stringify(v);if(typeof v==='number'){if(!Number.isFinite(v))fail('nonfinite');return JSON.stringify(v)}if(typeof v==='string')return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(canonical).join(',')}]`;if(!plain(v))fail('nonplain');return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`}
function sha(b){return createHash('sha256').update(b).digest('hex')}
function uid(){if(typeof process.geteuid!=='function')fail('geteuid required');return process.geteuid()}
function binding(raw){if(!plain(raw))fail('binding invalid');const keys=['operationId','logicalOperationIntentDigest','logicalWorkDigest','registrySha256','requestBodySha256'];if(Object.keys(raw).sort().join(',')!==[...keys].sort().join(','))fail('binding fields invalid');if(!OP.test(String(raw.operationId??'')))fail('operationId invalid');for(const k of keys.slice(1))if(!HEX64.test(String(raw[k]??'')))fail(`${k} invalid`);return Object.freeze({...raw})}
export function brokerAdmissionCapabilityIdV1(raw){const b=binding(raw);return `voidobac1_${sha(Buffer.concat([Buffer.from(`${ID_MARKER}\0`),Buffer.from(canonical({operation_id:b.operationId,logical_work_digest:b.logicalWorkDigest,registry_sha256:b.registrySha256,request_body_sha256:b.requestBodySha256}))]))}`}
export function brokerAdmissionSlotLeafV1(d){if(!HEX64.test(String(d??'')))fail('intent invalid');return `broker-admission-v1-${d}.json`}
async function rootHandle(root){if(!root?.handle)fail('root invalid');const st=await root.handle.stat({bigint:true});if(!st.isDirectory()||st.dev!==root.dev||st.ino!==root.ino||(Number(st.mode)&0o7777)!==0o700||Number(st.uid)!==uid())fail('root generation invalid');return root.handle}
async function pin(h){const st=await h.stat({bigint:true});if(!st.isDirectory()||(Number(st.mode)&0o7777)!==0o700||Number(st.uid)!==uid())fail('root fd invalid');return Object.freeze({handle:h,dev:st.dev,ino:st.ino,uid:Number(st.uid),mode:Number(st.mode)&0o7777})}
export async function openInheritedBrokerAdmissionRootV1(rawFd){const t=String(rawFd??'').trim();if(!/^[1-9][0-9]*$/.test(t))fail('root fd invalid');const fd=Number(t);if(!Number.isSafeInteger(fd)||fd<3||fd>1048575)fail('root fd bounds');const h=await fsOpen(`/proc/self/fd/${fd}`,FS.O_RDONLY|FS.O_DIRECTORY);try{return await pin(h)}catch(e){await h.close().catch(()=>{});throw e}}
function build(input){const b=binding(input.binding);if(!TRIAL.test(String(input.trialId??''))||!ADMISSION.test(String(input.admissionId??'')))fail('trial/admission invalid');for(const x of [input.admissionReceiptSha256,input.promptSha256])if(!HEX64.test(String(x??'')))fail('provenance digest invalid');if(!MODEL.test(String(input.model??''))||!CANON.test(String(input.canonicalSlug??'')))fail('model invalid');return {marker:MARKER,version:1,capability_id:brokerAdmissionCapabilityIdV1(b),operation_id:b.operationId,logical_operation_intent_digest:b.logicalOperationIntentDigest,logical_work_digest:b.logicalWorkDigest,registry_sha256:b.registrySha256,request_body_sha256:b.requestBodySha256,model:input.model,canonical_slug:input.canonicalSlug,trial_id:input.trialId,admission_id:input.admissionId,admission_receipt_sha256:input.admissionReceiptSha256,prompt_sha256:input.promptSha256}}
function bytes(v){return Buffer.from(`${JSON.stringify(v,null,2)}\n`)}
function validate(raw,expected){const ordered=['marker','version','capability_id','operation_id','logical_operation_intent_digest','logical_work_digest','registry_sha256','request_body_sha256','model','canonical_slug','trial_id','admission_id','admission_receipt_sha256','prompt_sha256'];if(!plain(raw)||Object.keys(raw).join(',')!==ordered.join(','))fail('capability fields/order invalid');if(raw.marker!==MARKER||raw.version!==1||!CAP.test(String(raw.capability_id??'')))fail('capability marker/id invalid');const b=binding(expected.binding);if(raw.capability_id!==brokerAdmissionCapabilityIdV1(b)||raw.operation_id!==b.operationId||raw.logical_operation_intent_digest!==b.logicalOperationIntentDigest||raw.logical_work_digest!==b.logicalWorkDigest||raw.registry_sha256!==b.registrySha256||raw.request_body_sha256!==b.requestBodySha256||raw.model!==expected.model||raw.canonical_slug!==expected.canonicalSlug)fail('capability work binding mismatch');if(!TRIAL.test(String(raw.trial_id??''))||!ADMISSION.test(String(raw.admission_id??''))||!HEX64.test(String(raw.admission_receipt_sha256??''))||!HEX64.test(String(raw.prompt_sha256??'')))fail('capability provenance invalid');return Object.freeze({capabilityId:raw.capability_id,trialId:raw.trial_id,admissionId:raw.admission_id,admissionReceiptSha256:raw.admission_receipt_sha256,promptSha256:raw.prompt_sha256})}
export async function publishBrokerAdmissionCapabilityV1(root,input){const h=await rootHandle(root),cap=build(input),leaf=brokerAdmissionSlotLeafV1(cap.logical_operation_intent_digest);await publishReceiptExact(`/proc/self/fd/${h.fd}/${leaf}`,cap);return readBrokerAdmissionCapabilityV1(root,{binding:input.binding,model:input.model,canonicalSlug:input.canonicalSlug})}
export async function readBrokerAdmissionCapabilityV1(root,expected){const dir=await rootHandle(root),b=binding(expected.binding),path=`/proc/self/fd/${dir.fd}/${brokerAdmissionSlotLeafV1(b.logicalOperationIntentDigest)}`,fh=await fsOpen(path,FS.O_RDONLY|FS.O_NOFOLLOW|FS.O_NONBLOCK);try{const pre=await fh.stat({bigint:true});if(!pre.isFile()||Number(pre.uid)!==root.uid||(Number(pre.mode)&0o7777)!==0o600||pre.nlink!==1n||pre.size<1n||pre.size>BigInt(MAX_BYTES))fail('capability file invalid');const data=Buffer.alloc(Number(pre.size));let p=0;while(p<data.length){const r=await fh.read(data,p,data.length-p,p);if(r.bytesRead===0)fail('short capability read');p+=r.bytesRead}const post=await fh.stat({bigint:true});for(const k of ['dev','ino','size','mtimeNs','ctimeNs'])if(pre[k]!==post[k])fail('capability changed during read');let raw;try{raw=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(data))}catch{fail('capability JSON invalid')}const out=validate(raw,expected);if(!data.equals(bytes(raw)))fail('capability bytes not exact');const vis=await fsLstat(path,{bigint:true});if(!vis.isFile()||vis.dev!==post.dev||vis.ino!==post.ino)fail('capability visible generation drifted');await rootHandle(root);return out}finally{await fh.close().catch(()=>{})}}
