#!/usr/bin/env node
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';

const P={doc:'docs/governance/void-brood-queen-private-broker-contract-v1.md',fix:'fixtures/governance/void-brood-queen-private-broker-contract-v1.json',id:'fixtures/governance/void-brood-queen-cryptographic-identity-contract-v1.json',seat:'fixtures/governance/void-brood-queen-local-model-seat-v1.json',wf:'.github/workflows/void-brood-queen-private-broker-contract-v1.yml'};
const MARK='VOID_BROOD_QUEEN_PRIVATE_BROKER_CONTRACT_V1_20260822';
const IDMARK='VOID_BROOD_QUEEN_CRYPTOGRAPHIC_IDENTITY_CONTRACT_V1_20260822';
const SEATMARK='VOID_BROOD_QUEEN_LOCAL_MODEL_SEAT_V1_20260822';
const IDHEAD='9f6b868607a9470710ec3143481b9f566a33c841', IDBLOB='2b0658867a2273e486cf685be30c368754f2b4b3';
const SEATHEAD='b43af85f92006970f29bd35a30341eb8881ac246', SEATBLOB='806296f0bc18c87471341fa9a89e4561a6acaa5b';
const PDOMAIN='VOID_BROOD_QUEEN_PARENT_POLICY_IDENTITY_V1', PSHA='a60109c80fae0e2cd7dc18bba9babea9edacaa33b11c07dabe77ae8a767412a3';
const DOMAIN='VOID_BROOD_QUEEN_PRIVATE_BROKER_POLICY_V1', GEN='1', SHA='3dfe1b4d40d298949026ed98d46e55a6b4723118a35900d188fc45afe8e6461c';
const CAPS=['analysis','drafting','proof_design','review','test_generation','bounded_task_planning','evidence_synthesis'];
const h=s=>createHash('sha256').update(s).digest('hex');
const blob=p=>execFileSync('git',['hash-object',p],{encoding:'utf8'}).trim();
const hold=m=>{throw new Error(m)};
const yes=(v,n)=>{if(v!==true)hold(`${n} must be true`)};
const no=(v,n)=>{if(v!==false)hold(`${n} must be false`)};
const arr=(a,b,n)=>{assert.deepEqual(a,b,`${n} drift`)};
const allTrue=(o,ks,prefix)=>ks.forEach(k=>yes(o?.[k],`${prefix}.${k}`));
const allFalse=(o,ks,prefix)=>ks.forEach(k=>no(o?.[k],`${prefix}.${k}`));

function transport(v){if(typeof v!=='string'||!/^[0-9a-f]{24}$/.test(v))hold('transport wire invalid');return{n:BigInt(`0x${v}`),nonce:Buffer.from(v,'hex')}}
function wire96(n){if(typeof n!=='bigint'||n<0n||n>=1n<<96n)hold('transport range');return n.toString(16).padStart(24,'0')}
function dec(v,bits,n){if(typeof v!=='string'||!/^(0|[1-9][0-9]*)$/.test(v))hold(`${n} wire invalid`);const x=BigInt(v);if(x>=1n<<BigInt(bits))hold(`${n} overflow`);return x}

function bootstrap(s,r){const e=s.boot.get(r.nonce);if(e)return e.ch===r.ch&&e.ap===r.ap&&e.sid===r.sid?{k:'dup',...e}:{k:'BOOTSTRAP_CONFLICT'};const x={ch:r.ch,ap:r.ap,sid:r.sid,receipt:`b:${r.ap}`};s.boot.set(r.nonce,x);s.sessions.set(r.sid,{generation:'0',next:'0',version:0,admissions:new Map(),successor:null});return{k:'commit',...x}}
function admit(s,r){const e=s.admissions.get(r.seq);if(e)return e.task===r.task?{k:'dup',e}:{k:'SEQUENCE_CONFLICT'};if(r.ver!==s.version)return{k:'CAS'};if(r.gen!==s.generation)return{k:'SESSION_STALE'};if(r.seq!==s.next)return{k:'SEQUENCE_CONFLICT'};const e2={task:r.task,seq:r.seq,gen:r.gen};s.admissions.set(r.seq,e2);s.next=(BigInt(s.next)+1n).toString();s.version++;return{k:'commit',e:e2}}
function rotate(s,r){if(r.ver!==s.version)return{k:'CAS'};if(r.from!==s.generation)return{k:'SESSION_STALE'};if(s.successor)return s.successor.hash===r.hash?{k:'dup',e:s.successor}:{k:'SESSION_FORK_CONFLICT'};const e={hash:r.hash,from:r.from,to:r.to,activationTaskSequence:s.next};s.successor=e;s.generation=r.to;s.version++;return{k:'commit',e}}
function stage(t,r){if(t.staged)return t.staged.hash===r.hash?{k:'dup',e:t.staged}:{k:'RESULT_CONFLICT',e:t.staged};t.staged=structuredClone(r);return{k:'commit',e:t.staged}}
function publish(t,sink){if(!t.staged)hold('publish before stage');const id=t.staged.receipt,p=`${t.staged.hash}:${id}`,e=sink.get(id);if(e!==undefined&&e!==p)hold('publication conflict');sink.set(id,p);t.published=id;return id}
function freshAead({certain,exhausted}){return certain&&!exhausted}

function adversaries(){
  const a=1n<<53n,b=a+1n,wa=wire96(a),wb=wire96(b);assert.notEqual(wa,wb);assert.notDeepEqual(transport(wa).nonce,transport(wb).nonce);assert.equal(transport('ffffffffffffffffffffffff').n,(1n<<96n)-1n);
  for(const x of [1,'FFFFFFFFFFFFFFFFFFFFFFFF','0xffffffffffffffffffffffff','fffffffffffffffffffffff','1000000000000000000000000','-00000000000000000000001','00000000000000000000000g'])assert.throws(()=>transport(x));
  assert.equal(dec('18446744073709551615',64,'task'),(1n<<64n)-1n);for(const x of [1,'01','-1','+1','1.0','1e3','18446744073709551616'])assert.throws(()=>dec(x,64,'task'));assert.equal(dec('4294967295',32,'gen'),(1n<<32n)-1n);assert.throws(()=>dec('4294967296',32,'gen'));
  const st={boot:new Map(),sessions:new Map()},r={nonce:'n',ch:'c',ap:'a',sid:'0123456789abcdef0123456789abcdef'};assert.equal(st.sessions.size,0);const b1=bootstrap(st,r);assert.equal(b1.k,'commit');assert.equal(bootstrap(st,r).k,'dup');assert.equal(bootstrap(st,{...r,ap:'x'}).k,'BOOTSTRAP_CONFLICT');assert.equal(st.sessions.size,1);
  const s=st.sessions.get(r.sid);assert.equal(admit(s,{ver:0,gen:'0',seq:'0',task:'t0'}).k,'commit');assert.equal(s.next,'1');assert.equal(admit(s,{ver:1,gen:'0',seq:'0',task:'t0'}).k,'dup');assert.equal(admit(s,{ver:1,gen:'0',seq:'0',task:'x'}).k,'SEQUENCE_CONFLICT');const rr=rotate(s,{ver:1,from:'0',to:'1',hash:'r01'});assert.equal(rr.k,'commit');assert.equal(rr.e.activationTaskSequence,'1');assert.equal(admit(s,{ver:1,gen:'0',seq:'1',task:'stale'}).k,'CAS');
  const t={staged:null,published:null};assert.equal(stage(t,{hash:'ha',receipt:'ra'}).k,'commit');assert.equal(stage(t,{hash:'ha',receipt:'ra'}).k,'dup');assert.equal(stage(t,{hash:'hb',receipt:'rb'}).k,'RESULT_CONFLICT');const sink=new Map();assert.equal(publish(t,sink),'ra');t.published=null;assert.equal(publish(t,sink),'ra');assert.equal(sink.size,1);
  assert.equal(freshAead({certain:false,exhausted:false}),false);assert.equal(freshAead({certain:true,exhausted:true}),false);assert.equal(freshAead({certain:true,exhausted:false}),true);assert.equal('owned'==='replacement',false);
}

async function main(){
  const [doc,ft,it,st,wf]=await Promise.all(Object.values(P).map(p=>readFile(p,'utf8')));const f=JSON.parse(ft),id=JSON.parse(it),seat=JSON.parse(st);
  if(f.marker!==MARK||id.marker!==IDMARK||seat.marker!==SEATMARK||f.parent_identity_contract_marker!==IDMARK||f.parent_local_seat_marker!==SEATMARK)hold('marker drift');
  if(f.parent_binding.domain!==PDOMAIN||f.parent_binding.identity_reviewed_head!==IDHEAD||f.parent_binding.identity_fixture_blob_sha!==IDBLOB||f.parent_binding.local_seat_reviewed_head!==SEATHEAD||f.parent_binding.local_seat_fixture_blob_sha!==SEATBLOB)hold('parent binding drift');
  if(blob(P.id)!==IDBLOB||blob(P.seat)!==SEATBLOB)hold('parent exact content drift');
  const pp=`${PDOMAIN}\nidentity_commit=${IDHEAD}\nidentity_fixture_blob=${IDBLOB}\nlocal_seat_commit=${SEATHEAD}\nlocal_seat_fixture_blob=${SEATBLOB}\n`;if(h(pp)!==PSHA||f.parent_binding.parent_policy_sha256!==PSHA)hold('parent policy digest drift');allTrue(f.parent_binding,['same_marker_parent_content_drift_fails_closed','bootstrap_rotation_task_receipt_bind_parent_policy_sha256'],'parent');
  if(f.network.chain_id!==2050||f.network.office!=='Brood Queen'||f.network.identity!=='Ren')hold('network/office drift');yes(f.network.provider_neutral,'provider neutrality');if(f.root_identity.algorithm!=='Ed25519')hold('root algorithm');allFalse(f.root_identity,['private_key_enters_model_context','private_key_enters_repository','private_key_enters_github','private_key_accessible_to_apollyon'],'root');
  if(f.broker_identity.algorithm!=='Ed25519')hold('broker algorithm');allTrue(f.broker_identity,['public_identity_pinned_before_bootstrap','bootstrap_challenge_signature_required','receipt_signed_by_broker_identity'],'broker');allFalse(f.broker_identity,['private_key_enters_model_context','transport_tls_alone_authenticates_crown_or_broker'],'broker');
  if(f.broker_identity.bootstrap_challenge_domain!=='VOID_BROOD_QUEEN_BROKER_BOOTSTRAP_CHALLENGE_V1'||f.broker_identity.crown_bootstrap_approval_domain!=='VOID_BROOD_QUEEN_CROWN_BOOTSTRAP_APPROVAL_V1'||f.broker_identity.receipt_signature_domain!=='VOID_BROOD_QUEEN_BROKER_RECEIPT_V1')hold('broker domains');
  allTrue(f.bootstrap_transaction,['challenge_single_use','challenge_binds_proposed_session_id','crown_approval_binds_proposed_session_id','consume_challenge_approval_and_create_session_atomic','commit_durable_before_success_receipt_release','exact_replay_after_commit_returns_same_session_and_receipt','at_most_one_session_per_crown_approval'],'bootstrap');no(f.bootstrap_transaction.crash_before_commit_creates_session_authority,'bootstrap crash authority');if(f.bootstrap_transaction.proposed_session_id_wire!=='lower_hex_32'||f.bootstrap_transaction.same_nonce_different_transcript_or_approval_terminal!=='BOOTSTRAP_CONFLICT')hold('bootstrap wire/terminal');
  if(f.policy.domain!==DOMAIN||f.policy.generation_wire!==GEN||f.policy.generation_type!=='canonical_u64_decimal_string')hold('policy identity');arr(f.policy.capability_ceiling,CAPS,'caps');const pre=`${DOMAIN}\nparent_policy_sha256=${PSHA}\npolicy_generation=${GEN}\ncapability_ceiling=${CAPS.join(',')}\nvalidator_capability_present=false\n`;if(h(pre)!==SHA||f.policy.sha256!==SHA)hold('policy digest');allFalse(f.policy,['validator_capability_present','authentication_implies_capability','session_rotation_can_expand_ceiling'],'policy');yes(f.policy.policy_or_ceiling_widening_requires_root_authenticated_boundary,'policy root boundary');
  if([f.crypto_profile.root_signature,f.crypto_profile.broker_identity_signature,f.crypto_profile.session_signature].some(x=>x!=='Ed25519')||f.crypto_profile.key_agreement!=='X25519'||f.crypto_profile.kdf!=='HKDF-SHA-256'||f.crypto_profile.aead!=='ChaCha20-Poly1305')hold('crypto profile');allTrue(f.crypto_profile,['all_zero_x25519_shared_secret_rejected','directional_traffic_key_separation','ciphertext_sha256_is_not_aad_or_plaintext_input'],'crypto');allFalse(f.crypto_profile,['algorithm_agility_within_v1_session','ecdsa_substitution_allowed','traffic_key_reused_across_generations','traffic_key_reused_across_directions'],'crypto');
  if(f.wire_encoding.transport_sequence_type!=='lower_hex_24'||f.wire_encoding.transport_sequence_regex!=='^[0-9a-f]{24}$'||f.wire_encoding.transport_sequence_nonce_derivation!=='hex_decode_12_bytes'||f.wire_encoding.transport_sequence_max_wire!=='ffffffffffffffffffffffff')hold('wire profile');allFalse(f.wire_encoding,['transport_sequence_json_number_allowed','transport_sequence_binary64_coercion_allowed','authority_counter_json_numbers_allowed','canonical_decimal_leading_zero_allowed','canonical_decimal_exponent_allowed','canonical_decimal_fraction_allowed','canonical_decimal_sign_allowed'],'wire');
  allTrue(f.outbound_transport_journal,['applies_both_directions','reservation_durable_before_aead_invocation','reservation_binds_exact_message_identity','protected_bytes_durable_before_first_release','retry_retransmits_exact_staged_protected_bytes','reserved_sequence_never_recycled_for_different_message','receiver_conflict_check_is_not_primary_nonce_safety','pre_staged_exact_rotation_retransmission_allowed','otherwise_requires_hold_or_root_authenticated_out_of_band_recovery'],'journal');allFalse(f.outbound_transport_journal,['uncertain_or_exhausted_old_generation_can_encrypt_fresh_rotation','uncertain_or_exhausted_old_generation_can_invoke_fresh_aead'],'journal');
  allTrue(f.session_authority,['one_durable_record_contains_active_generation_and_next_task_cursor','record_has_compare_and_swap_version','task_admission_and_rotation_share_same_cas_record','one_active_generation_atomically_bound','at_most_one_accepted_successor_transition','successor_may_preserve_or_reduce_capability_ceiling','stale_generation_may_only_retransmit_exact_accepted_transition','rotation_winner_rejects_paused_stale_admission_without_cursor_consumption','admission_winner_advances_exact_boundary_before_rotation'],'session');allFalse(f.session_authority,['successor_may_widen_capability_ceiling','successor_may_change_policy_root_without_root_boundary','stale_generation_fresh_transition_authority_after_successor_activation'],'session');if(f.session_authority.alternate_stale_successor_terminal!=='SESSION_FORK_CONFLICT')hold('successor terminal');
  allTrue(f.task_identity,['content_addressed','binds_session_id','binds_session_generation','binds_task_sequence','binds_capabilities','binds_capability_ceiling_digest','binds_payload_digest','binds_policy_generation','binds_policy_sha256','binds_parent_policy_sha256'],'task');if(f.task_identity.prefix!=='voidbqt1_')hold('task prefix');allTrue(f.atomic_task_admission,['cas_binds_session_authority_record_version','cas_binds_active_generation','cas_binds_predecessor_task_cursor','cas_binds_exact_canonical_task_identity','admitted_and_cursor_advance_one_atomic_commit','crash_before_commit_leaves_cursor_unchanged','crash_after_commit_exact_duplicate_returns_same_admission'],'admission');no(f.atomic_task_admission.executor_handoff_before_atomic_commit,'early executor handoff');
  arr(f.durable_state_machine.states,['RECEIVED','ADMITTED','EXECUTING','RESULT_STAGED','RESULT_PUBLISHED','COMPLETE'],'states');arr(f.durable_state_machine.fail_closed_terminals,['REJECTED','EXPIRED','REVOKED','BOOTSTRAP_CONFLICT','SEQUENCE_CONFLICT','TRANSPORT_SEQUENCE_CONFLICT','SESSION_FORK_CONFLICT','SESSION_STALE','POLICY_MISMATCH','EXECUTION_OUTCOME_UNKNOWN','RESULT_CONFLICT','FOREIGN_STATE_CONFLICT'],'terminals');allTrue(f.durable_state_machine,['admitted_durable_before_inference','safe_retry_from_execution_outcome_unknown_requires_separate_idempotent_executor_contract','result_stage_insert_if_absent','result_stage_first_writer_wins','identical_duplicate_completion_returns_existing_stage','result_staged_durable_before_publication','publication_consumes_only_immutable_staged_generation','publication_receipt_identity_is_idempotency_key','publication_sink_must_support_receipt_idempotency','crash_after_sink_publish_retries_same_logical_receipt','complete_binds_one_authoritative_result_hash','recovery_state_object_identity_cas','foreign_replacement_never_adopted_overwritten_or_deleted'],'state');allFalse(f.durable_state_machine,['executing_restart_without_staged_result_auto_reexecutes_inference','exactly_once_model_execution_claimed'],'state');if(f.durable_state_machine.executing_restart_without_staged_result_terminal!=='EXECUTION_OUTCOME_UNKNOWN'||f.durable_state_machine.different_completion_after_stage_terminal!=='RESULT_CONFLICT')hold('state terminal');
  if(f.apollyon.office!=='General')hold('Apollyon office');yes(f.apollyon.subordinate_compute,'Apollyon subordinate');allFalse(f.apollyon,['authenticated_crown_endpoint','may_receive_root_key','may_receive_session_private_key','may_receive_broker_identity_private_key','may_receive_validator_key','model_output_is_authoritative_receipt'],'Apollyon');yes(f.private_context.stays_local_on_precision,'context local');allFalse(f.private_context,['sent_as_blob_to_remote_provider','receipt_exposes_context_bytes','receipt_exposes_local_path'],'context');yes(f.revocation.canonical_role_revalidation_required,'role revalidation');yes(f.revocation.bounded_role_freshness_required_before_task_admission,'role freshness');allFalse(f.revocation,['cached_role_truth_survives_revocation','stale_generation_can_issue_ordinary_tasks'],'revocation');
  allFalse(f.threat_model,['github_authenticates_crown_session','transport_tls_alone_authenticates_crown_session','model_self_claim_authenticates_crown_session','task_result_substitution_preserves_identity','same_aead_key_nonce_can_protect_distinct_messages','sender_crash_can_recycle_nonce_for_different_message','uncertain_nonce_recovery_can_emit_fresh_old_generation_ciphertext','stale_generation_can_create_fresh_successor_fork','same_marker_parent_content_drift_preserves_child_policy_identity','restart_during_execution_claims_exactly_once_model_execution','concurrent_different_results_can_overwrite_staged_result','rotation_and_admission_can_commit_from_same_stale_authority_snapshot','one_crown_approval_can_mint_multiple_sessions'],'threat');yes(f.threat_model.duplicate_delivery_idempotent,'duplicate idempotence');allTrue(f.strongest_invariant,['at_most_one_session_per_crown_approval','at_most_one_admitted_task_per_session_sequence','at_most_one_immutable_result_stage_per_task','at_most_one_authoritative_completed_result_hash_per_task_id','does_not_claim_exactly_once_model_execution','no_capability_expansion_beyond_exact_list','no_distinct_messages_share_aead_key_nonce_pair','nonce_safety_survives_sender_crash','uncertain_or_exhausted_old_generation_has_zero_fresh_aead_authority','no_stale_generation_successor_fork','parent_policy_identity_content_bound','no_validator_authority_path','no_crown_broker_or_session_private_material_in_model_context'],'invariant');Object.entries(f.activation).forEach(([k,v])=>no(v,`activation.${k}`));
  for(const x of ['scripts/ci_diff_hygiene_v1.sh','scripts/prove_ci_diff_hygiene_v1.mjs','run: node scripts/prove_ci_diff_hygiene_v1.mjs','CI_DIFF_PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}','CI_DIFF_CURRENT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}','CI_DIFF_CHECKOUT_SHA: ${{ github.sha }}','CI_DIFF_BASE_REMOTE: ${{ github.server_url }}/${{ github.repository }}.git','CI_DIFF_HEAD_REMOTE: ${{ github.server_url }}/${{ github.event.pull_request.head.repo.full_name || github.repository }}.git','run: bash scripts/ci_diff_hygiene_v1.sh','fetch-depth: 1','persist-credentials: false'])if(!wf.includes(x))hold(`workflow binding missing: ${x}`);if(wf.includes('run: git diff --check'))hold('working-tree-only diff hygiene retained');
  adversaries();
  for(const x of [MARK,PSHA,SHA,'VOID_BROOD_QUEEN_SESSION_ROTATION_V1','transport_sequence` is exactly 24 lowercase hexadecimal characters','aead_nonce = hex_decode_12_bytes(transport_sequence)','one durable **session authority record**','`ADMITTED(task)` **and** advances the next-task cursor together','first-writer-wins','publication idempotency key','zero authority to create fresh protected bytes','BOOTSTRAP_CONFLICT','EXECUTION_OUTCOME_UNKNOWN','Exactly-once model execution is not claimed.','Validator capability is structurally absent from this broker contract.'])if(!doc.includes(x))hold(`doc binding missing: ${x}`);
  for(const rx of [/-----BEGIN [A-Z ]*PRIVATE KEY-----/,/\bsk-(?:proj-)?[A-Za-z0-9_-]{16,}\b/,/\bgithub_pat_[A-Za-z0-9_]{20,}\b/,/\bAKIA[0-9A-Z]{16}\b/])if(rx.test(ft))hold(`secret-like material: ${rx}`);
  console.log('VOID_BROOD_QUEEN_PRIVATE_BROKER_CONTRACT_V1_PROOF_GREEN');
  for(const x of ['transport_wire_exact_96_bit','adjacent_2pow53_values_distinct','bootstrap_single_use_atomic','task_admission_cursor_atomic','rotation_admission_shared_cas','result_stage_first_writer_wins','publication_receipt_idempotent','uncertain_old_generation_fresh_aead=false','foreign_state_recovery_fail_closed','committed_range_diff_hygiene_bound'])console.log(`${x}=true`.replace('=false=true','=false'));
}
main().catch(e=>{console.error(`HOLD: ${e?.message??String(e)}`);process.exitCode=2});
