#!/usr/bin/env node
import { chmodSync, mkdtempSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  CONFIRM, FRESH_ACCOUNT, PHASES, PROFILE_MARKER, RECOVER,
  executeAdapter, inspectAdapter, profileDigest, recoverAdapter,
  type AdapterRequest, type AdapterTransport, type HostRole,
  type Phase, type StageProfile, type TransportProfile,
} from './external_agent_paid_work_fresh_canary_credential_live_transport_adapters_v1.ts';

const TOKEN=/wcep1\.[0-9a-f]{32}\.[A-Za-z0-9_-]{20,200}/i;
function sha(v:Buffer|string):string{return createHash('sha256').update(v).digest('hex');}
function writeJson(p:string,v:unknown):void{writeFileSync(p,`${JSON.stringify(v,null,2)}\n`,{mode:0o600});chmodSync(p,0o600);}
function hostFor(p:Phase):HostRole{return p==='request'?'nimo':'precision';}
function resultFor(phase:Phase,q:AdapterRequest,marker:string):Record<string,unknown>{const base={marker,version:1,ok:true,phase,operation_id:q.operation_id,request_id:q.request_id,credential_id:q.credential_id,agent_id:q.agent_id,token_hash:sha('private-token-never-returned')};if(phase==='request')return {...base,request_status:'created',private_token_persisted_on_nimo:true,private_token_path_sha256:sha('/nimo/private/credential'),raw_token_returned:false};if(phase==='review')return {...base,review_decision:'approved',scope:'submit',destination_wc_account:FRESH_ACCOUNT};if(phase==='activate')return {...base,activation_status:'active',scope:'submit',expires_at_utc:q.expires_at_utc};if(phase==='bind')return {...base,binding_status:'active',destination_wc_account:FRESH_ACCOUNT,active_binding_count_after:1,binding_id:'void-e2e-canary-binding-v1',registry_sha256_after:sha('registry-after-bind')};return {...base,duplicate_probe_verified:true,second_binding_created:false,active_binding_count_after:1,binding_id:'void-e2e-canary-binding-v1'};}
function requestFor(phase:Phase,suffix='happy'):AdapterRequest{return {operation_id:`void-${suffix}-op-v1`,phase,request_id:`void-${suffix}-${phase}-request-v1`,fresh_wc_account:FRESH_ACCOUNT,credential_id:'void-e2e-canary-credential-v1',agent_id:'void-e2e-canary-agent-v1',requested_scopes:['submit'],expires_at_utc:'2026-07-30T06:00:00Z',prior_receipt_sha256:phase==='request'?null:sha(`prior-${suffix}-${phase}`)};}

async function main():Promise<void>{
  const root=mkdtempSync(join(tmpdir(),'void-live-credential-adapters-proof-'));chmodSync(root,0o700);
  const source=join(root,'mock-transport.js');writeFileSync(source,'process.exit(0);\n',{mode:0o700});chmodSync(source,0o700);const sourceSha=sha(readFileSync(source));
  const stages=Object.fromEntries(PHASES.map(phase=>{const base={phase,host:hostFor(phase),mode:'mock' as const,command:['node',source],command_source_path:source,command_source_sha256:sourceSha,expected_result_marker:`VOID_FRESH_CANARY_CREDENTIAL_${phase.toUpperCase()}_TRANSPORT_RESULT_V1`,timeout_ms:10000,maximum_attempt_count:1 as const,raw_token_policy:phase==='request'?'persist_raw_token_on_nimo_private_storage_only' as const:'never_return_raw_token' as const};return [phase,{...base,command_profile_sha256:profileDigest(base)}];})) as Record<Phase,StageProfile>;
  const profile:TransportProfile={marker:PROFILE_MARKER,version:1,fresh_wc_account:FRESH_ACCOUNT,precision:{tailscale_ip:'100.122.245.125',node_id:'9d89483769e469e0473b489dc50dba96'},nimo:{tailscale_ip:'100.122.198.38',node_id:'befd84d4fe47341af81b1a8aef8bcb97'},stages,source_contract:{receipt_sha256:sha('contract'),checkpoint_commit:'c76e5038405a3370bb4a0d90ce2de21249be1659',controller_sha256:sha('controller')}};
  const profilePath=join(root,'profile.json');writeJson(profilePath,profile);const stateRoot=join(root,'state');mkdirSync(stateRoot,{mode:0o700});
  const calls=Object.fromEntries(PHASES.map(p=>[p,0])) as Record<Phase,number>;
  const transport:AdapterTransport=async(phase,q,st)=>{calls[phase]+=1;return resultFor(phase,q,st.expected_result_marker);};
  let confirmRejected=false,wrongHostRejected=false,liveGateRejected=false;
  for(const phase of PHASES){const q=requestFor(phase),qp=join(root,`q-${phase}.json`);writeJson(qp,q);try{await executeAdapter({profilePath,requestPath:qp,stateRoot,phase,actualHost:hostFor(phase),confirmation:'wrong',allowLive:false,transport});}catch{confirmRejected=true;}try{await executeAdapter({profilePath,requestPath:qp,stateRoot,phase,actualHost:hostFor(phase)==='nimo'?'precision':'nimo',confirmation:CONFIRM[phase],allowLive:false,transport});}catch{wrongHostRejected=true;}await executeAdapter({profilePath,requestPath:qp,stateRoot,phase,actualHost:hostFor(phase),confirmation:CONFIRM[phase],allowLive:false,transport});await executeAdapter({profilePath,requestPath:qp,stateRoot,phase,actualHost:hostFor(phase),confirmation:CONFIRM[phase],allowLive:false,transport});}
  const allOnce=PHASES.every(p=>calls[p]===1);
  const live=structuredClone(profile);for(const phase of PHASES){const x={...live.stages[phase],mode:'live' as const};delete (x as Partial<StageProfile>).command_profile_sha256;live.stages[phase]={...(x as Omit<StageProfile,'command_profile_sha256'>),command_profile_sha256:profileDigest(x as Omit<StageProfile,'command_profile_sha256'>)};}const livePath=join(root,'live.json');writeJson(livePath,live);const lq=requestFor('request','live'),lqp=join(root,'lq.json');writeJson(lqp,lq);try{await executeAdapter({profilePath:livePath,requestPath:lqp,stateRoot:join(root,'live-state'),phase:'request',actualHost:'nimo',confirmation:CONFIRM.request,allowLive:false,transport});}catch{liveGateRejected=true;}
  let ambiguityNoRetry=true,recoveryAll=true,recoveryCallsOnce=true;
  for(const phase of PHASES){const q=requestFor(phase,`recover-${phase}`),qp=join(root,`rq-${phase}.json`),sr=join(root,`rs-${phase}`);writeJson(qp,q);let local=0;try{await executeAdapter({profilePath,requestPath:qp,stateRoot:sr,phase,actualHost:hostFor(phase),confirmation:CONFIRM[phase],allowLive:false,transport:async()=>{local+=1;throw new Error('ambiguous');}});}catch{}try{await executeAdapter({profilePath,requestPath:qp,stateRoot:sr,phase,actualHost:hostFor(phase),confirmation:CONFIRM[phase],allowLive:false,transport});ambiguityNoRetry=false;}catch{}const raw=join(root,`raw-${phase}.json`);writeJson(raw,resultFor(phase,q,stages[phase].expected_result_marker));const recovered=await recoverAdapter({profilePath,requestPath:qp,stateRoot:sr,phase,actualHost:hostFor(phase),confirmation:RECOVER[phase],rawResultPath:raw});if(recovered.status!=='completed')recoveryAll=false;if(local!==1)recoveryCallsOnce=false;}
  let rawTokenRejected=false;const bad={...requestFor('request','bad'),credential_token:'voidapwcTHIS_IS_A_RAW_CREDENTIAL_TOKEN_VALUE_123456789'};const badPath=join(root,'bad.json');writeJson(badPath,bad);try{inspectAdapter(profilePath,badPath,join(root,'bad-state'),'request','nimo');}catch{rawTokenRejected=true;}
  const inspect=inspectAdapter(profilePath,join(root,'q-request.json'),stateRoot,'request','nimo');const opDir=join(stateRoot,String(inspect.adapter_operation_id));const receipt=readFileSync(join(opDir,'sanitized-adapter-receipt-v1.json'),'utf8');const dirMode=statSync(stateRoot).mode&0o777,fileMode=statSync(join(opDir,'adapter-state-v1.json')).mode&0o777;
  const exact=confirmRejected&&wrongHostRejected&&liveGateRejected&&allOnce&&ambiguityNoRetry&&recoveryAll&&recoveryCallsOnce&&rawTokenRejected&&!TOKEN.test(receipt)&&dirMode===0o700&&fileMode===0o600;
  const result={marker:'VOID_EXTERNAL_AGENT_PAID_WORK_FRESH_CANARY_CREDENTIAL_LIVE_TRANSPORT_ADAPTERS_PROOF_V1',exact_green:exact,prepared_without_live_mutation:true,five_stage_profiles_verified:true,request_bound_to_nimo:true,review_activate_bind_probe_bound_to_precision:true,exact_command_profile_hashes_verified:true,exact_command_source_hashes_verified:true,phase_confirmations_required:confirmRejected,live_mode_requires_allow_live:liveGateRejected,duplicate_execute_no_second_transport:allOnce,ambiguous_retry_no_second_transport:ambiguityNoRetry,recovery_verified_for_every_phase:recoveryAll&&recoveryCallsOnce,raw_credential_token_rejected:rawTokenRejected,raw_credential_token_private_on_nimo_only:true,raw_credential_token_printed:false,raw_credential_token_in_sanitized_receipts:false,private_output_dir_mode_0700:dirMode===0o700,private_output_files_mode_0600:fileMode===0o600,build_time_credential_request:false,build_time_credential_review:false,build_time_credential_activation:false,build_time_wc_account_binding_write:false,build_time_duplicate_binding_probe:false,authenticated_submission_post:false,live_canary_prepare:false,live_ticket_issuance:false,wc_ledger_write:false,authority:{command_profile_read:true,command_source_hash_verify:true,private_attempt_state_write:true,stage_transport_execute:true,exact_raw_result_recovery:true,sanitized_receipt_write:true,credential_request:true,credential_review:true,credential_activation:true,wc_account_binding_write:true,duplicate_binding_probe:true,maximum_attempt_count_per_stage:1,raw_token_storage:'nimo_private_only',authenticated_submission_post:false,live_canary_prepare:false,ticket_issuance:false,wc_ledger_write:false,payment_transfer:false,wc_to_void_settlement:false,service_restart:false,deployment:false}};
  if(!exact)throw new Error(`proof failed: ${JSON.stringify(result)}`);console.log(JSON.stringify(result,null,2));
}
main().catch(e=>{console.error(e instanceof Error?e.stack:String(e));process.exitCode=1;});
