#!/usr/bin/env node
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import http from "node:http";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawn } from "node:child_process";

const MARKER = "VOID_TOR_AGENT_DISCOVERY_PARITY_V1_PROOF_GREEN";
function fail(m){throw new Error(m)}
function load(p){return JSON.parse(readFileSync(p,"utf8"))}
function sha(p){return createHash("sha256").update(readFileSync(p)).digest("hex")}
function eq(a,b,l){if(a!==b) fail(`${l} mismatch: expected=${b} actual=${a}`)}
function ok(v,l){if(!v) fail(l)}
function request(port,path,method="GET") { return new Promise((resolveRequest,reject)=>{ const req=http.request({host:"127.0.0.1",port,path,method,headers:{host:`127.0.0.1:${port}`,accept:"application/json"}},res=>{const chunks=[];res.on("data",c=>chunks.push(c));res.on("end",()=>resolveRequest({status:res.statusCode,headers:res.headers,body:Buffer.concat(chunks)}));});req.setTimeout(3000,()=>req.destroy(new Error("timeout")));req.on("error",reject);req.end();}); }
async function startServer(root,hostnameFile){return await new Promise((resolveStart,reject)=>{const child=spawn(process.execPath,["tools/void-tor-onion-public-node-v1.mjs","--host","127.0.0.1","--port","0","--hostname-file",hostnameFile],{cwd:root,stdio:["ignore","pipe","pipe"]});let out="",err="",done=false;const timer=setTimeout(()=>{child.kill("SIGKILL");reject(new Error(`server start timeout stdout=${out} stderr=${err}`));},5000);child.stdout.on("data",c=>{out+=c;const m=out.match(/(?:^|\n)port=(\d+)(?:\n|$)/);if(m&&!done){done=true;clearTimeout(timer);resolveStart({child,port:Number(m[1]),stdout:()=>out,stderr:()=>err});}});child.stderr.on("data",c=>err+=c);child.on("exit",code=>{if(!done){clearTimeout(timer);reject(new Error(`server exited ${code} stdout=${out} stderr=${err}`));}});});}
async function main(){
 const root=process.cwd();
 const profile=load(resolve(root,"config/void-tor-agent-discovery-parity-v1.json"));
 eq(profile.marker,"VOID_TOR_AGENT_DISCOVERY_PARITY_PROFILE_V1","profile marker"); eq(profile.version,1,"profile version"); eq(profile.routes.length,14,"route count");
 const paths=profile.routes.map(r=>r.path); eq(new Set(paths).size,paths.length,"unique route paths");
 for(const [path,digest] of Object.entries(profile.source_bindings)){eq(sha(resolve(root,path)),digest,`source binding ${path}`)}
 const rootDoc=load(resolve(root,"public/.well-known/void-public-node.json")); eq(rootDoc.marker,"VOID_PUBLIC_NODE_AGENT_DISCOVERY_V1","root marker"); eq(rootDoc.effective_base_url,profile.transport.base_url,"root base"); eq(rootDoc.parity.expected_client_discovery_parity,"full","parity classification"); eq(rootDoc.parity.route_count,14,"root route count");
 ok(rootDoc.authority.read_only===true,"root read_only missing"); for(const key of ["mutation_authority_granted","paid_work_submission","payment_execution","work_credit_write","wallet_or_signer_access","node_runtime_mutation","operator_control"]) ok(rootDoc.authority[key]===false,`authority ${key} not false`);
 for(const [id,url] of Object.entries(rootDoc.links)){ok(url.startsWith(`${profile.transport.base_url}/`),`cross-origin link ${id}`); const u=new URL(url); ok(!u.search&&!u.hash,`query or fragment in ${id}`)}
 const canonical=load(resolve(root,"public/public-node/agents/paid-work-v1.json")); const alias=load(resolve(root,"public/public-node/agent-paid-work-public-discovery-v1.json")); const expected=structuredClone(canonical); expected.$schema="/public-node/agents/paid-work-v1.schema.json"; expected.routes={self:"/public-node/agent-paid-work-public-discovery-v1.json",schema:"/public-node/agents/paid-work-v1.schema.json",canonical_agent_discovery:"/public-node/agents/discovery-v1.json"}; eq(JSON.stringify(alias),JSON.stringify(expected),"paid-work alias");
 eq(alias.marker,"VOID_AGENT_PAID_WORK_RUNTIME_DISCOVERY_V1","paid-work marker"); eq(alias.status,"read_only_protocol_discovery_live","paid-work status"); ok(alias.authority.mutation_authority_granted===false,"paid-work mutation authority"); ok(alias.runtime_capabilities.live_payment_execution==="unavailable","paid-work payment honesty");
 const serverSource=readFileSync(resolve(root,"tools/void-tor-onion-public-node-v1.mjs"),"utf8"); for(const token of ["safeResolveStatic","if (parsed.search || parsed.hash) return { error: 404 }","new Set([\"GET\", \"HEAD\"])"]) ok(serverSource.includes(token),`server safety token missing: ${token}`);
 const tmp=mkdtempSync(join(tmpdir(),"void-discovery-parity-proof-")); const hostname=join(tmp,"hostname"); writeFileSync(hostname,`${profile.transport.onion_hostname}\n`,{mode:0o600}); let server;
 try { server=await startServer(root,hostname); const rootPath="/.well-known/void-public-node.json", paidPath="/public-node/agent-paid-work-public-discovery-v1.json"; for(const [path,file] of [[rootPath,"public/.well-known/void-public-node.json"],[paidPath,"public/public-node/agent-paid-work-public-discovery-v1.json"]]){const get=await request(server.port,path);eq(get.status,200,`${path} GET status`);eq(createHash("sha256").update(get.body).digest("hex"),sha(resolve(root,file)),`${path} body sha`);const head=await request(server.port,path,"HEAD");eq(head.status,200,`${path} HEAD status`);eq(head.body.length,0,`${path} HEAD body`);eq(Number(head.headers["content-length"]),readFileSync(resolve(root,file)).length,`${path} HEAD content-length`);const query=await request(server.port,`${path}?cache=1`);eq(query.status,404,`${path} query status`);const post=await request(server.port,path,"POST");eq(post.status,405,`${path} POST status`);} for(const path of ["/.well-known/void-agent-discovery.json","/.well-known/void-network-authenticity.json","/public-node/agents/discovery-v1.json","/public-node/agents/capabilities-v1.json","/public-node/agents/authentication-v1.json","/public-node/agents/first-contact-v1.json","/public-node/agents/paid-work-v1.json"]){const res=await request(server.port,path);eq(res.status,200,`${path} existing route status`);} }
 finally { if(server){server.child.kill("SIGTERM"); await new Promise(r=>setTimeout(r,100)); if(!server.child.killed)server.child.kill("SIGKILL");} rmSync(tmp,{recursive:true,force:true}); }
 console.log(MARKER); console.log("generated_documents_exact=true"); console.log("public_node_root_exact=true"); console.log("paid_work_alias_exact=true"); console.log("existing_agent_routes_preserved=true"); console.log("query_variants_rejected=true"); console.log("get_head_only=true"); console.log("expected_client_discovery_parity=full"); console.log("mutation=false"); console.log("payment_execution=false"); console.log("fund_movement=false");
}
main().catch(e=>{console.error("VOID_TOR_AGENT_DISCOVERY_PARITY_V1_PROOF_FAIL");console.error(e instanceof Error?e.stack||e.message:String(e));process.exit(1)});
