import assert from 'node:assert/strict';
import {MEMBER_SCHEMA,MAJORS,PROFILES,TIERS,ARTIFACTS,MUTABLE,CUTS,TERMS,sha256,falseAuthority,validateMember,buildTier,validateTier,buildTwoTier,validateTwoTier,canonical} from './lib/void_datanet_executed_byte_receipt_dag_v1.mjs';
const HEAD='1'.repeat(40),TREE='2'.repeat(40),GEN='contract-v1';const exp=r=>sha256(`expected:${r}`),mark=r=>sha256(`marked:${r}`);
const expected=()=>Object.fromEntries(ARTIFACTS.map(r=>[r,{path:`/evidence/${r}`,bytes:4096+r.length,sha256:exp(r)}]));
const opened=(r,d=exp(r))=>({path:`/proc/opened/${r}`,dev:7,ino:1000+ARTIFACTS.indexOf(r),bytes:4096+r.length,sha256:d,opened_by_kernel:true});
function sched(profile,a,c,t,kind,marked=false){const e=expected(),o=Object.fromEntries(ARTIFACTS.map(r=>[r,opened(r)]));if(marked)o[a]=opened(a,mark(a));return{id:`${a}:${c}:${t}:${kind}`,kind,artifact_class:a,cut_point:c,termination_mode:t,generation:GEN,path_sha256_before:exp(a),path_sha256_after:exp(a),expected:e,opened:o,marked_execution:marked,accepted_substituted_identity:marked,writable_aliases:profile==='protected'?0:(marked?1:0),writable_vmas:0,partial_evidence_discarded:kind==='attack'&&t==='supervisor_crash',recovery_ticks:t==='supervisor_crash'?7:0,projection_sha256:sha256('projection-v1')};}
function member(tier,major,profile){const schedules=[];let used=false;for(const a of MUTABLE)for(const c of CUTS)for(const t of TERMS){const marked=profile==='current'&&!used;schedules.push(sched(profile,a,c,t,'attack',marked));schedules.push(sched(profile,a,c,t,'recovery_control'));used||=marked;}return{schema:MEMBER_SCHEMA,head:HEAD,tree:TREE,generation:GEN,host_tier:tier,major,profile,schedule_manifest_sha256:sha256('manifest-v1'),source_inventory_sha256:sha256('inventory-v1'),schedules,authority:falseAuthority()};}
const tiers=[];for(const tier of TIERS){const ms=MAJORS.flatMap(m=>PROFILES.map(p=>member(tier,m,p)));ms.forEach(validateMember);const t=buildTier(ms);validateTier(t);tiers.push(t);}const final=buildTwoTier(tiers);validateTwoTier(final);
const rejects=[];const bad=(name,fn)=>{const m=structuredClone(member('hosted',22,'protected'));fn(m);assert.throws(()=>validateMember(m));rejects.push(name);};
bad('protected-marked',m=>{const s=m.schedules[0];s.marked_execution=s.accepted_substituted_identity=true;s.opened[s.artifact_class].sha256=mark(s.artifact_class);});bad('writable-fd',m=>m.schedules[0].writable_aliases=1);bad('writable-vma',m=>m.schedules[0].writable_vmas=1);bad('missing-schedule',m=>m.schedules.pop());bad('duplicate-schedule',m=>m.schedules[1]=structuredClone(m.schedules[0]));bad('wrong-generation',m=>m.schedules[0].generation='other');bad('late-recovery',m=>m.schedules[0].recovery_ticks=65);bad('crash-partial',m=>m.schedules.find(s=>s.kind==='attack'&&s.termination_mode==='supervisor_crash').partial_evidence_discarded=false);bad('path-drift',m=>m.schedules[0].path_sha256_after='3'.repeat(64));bad('not-kernel-opened',m=>m.schedules[0].opened.runtime.opened_by_kernel=false);bad('authority',m=>m.authority.source_green=true);bad('unknown-key',m=>m.extra=true);
const noSensitivity=member('hosted',22,'current');for(const s of noSensitivity.schedules){s.marked_execution=s.accepted_substituted_identity=false;s.opened[s.artifact_class].sha256=s.expected[s.artifact_class].sha256;s.writable_aliases=0;}assert.throws(()=>validateMember(noSensitivity));rejects.push('current-sensitivity');
const hosted=MAJORS.flatMap(m=>PROFILES.map(p=>member('hosted',m,p)));assert.throws(()=>buildTier(hosted.slice(0,5)));rejects.push('missing-tier-member');const dup=[...hosted];dup[5]=structuredClone(dup[4]);assert.throws(()=>buildTier(dup));rejects.push('duplicate-tier-member');assert.throws(()=>buildTwoTier([tiers[0],tiers[0]]));rejects.push('duplicate-tier');
console.log('VOID_DATANET_EXECUTED_BYTE_RECEIPT_DAG_V1_GREEN');console.log('synthetic_contract_only=true');console.log('natural_hosted_evidence=false');console.log('designated_host_evidence=false');console.log('members_per_tier=6');console.log('schedules_per_member=48');console.log(`mutant_rejections=${rejects.length}`);console.log(`contract_sha256=${sha256(canonical(final))}`);
