export const EARN_SCHEMA_PROOF_NOW_MS =
  Date.parse("2026-09-29T12:00:00.000Z");
export const EARN_SCHEMA_PROOF_NOW =
  new Date(EARN_SCHEMA_PROOF_NOW_MS).toISOString();

export function validEarnSnapshotV1({
  account = "account-A",
  generatedAt = EARN_SCHEMA_PROOF_NOW,
} = {}) {
  return {
    ok: true,
    marker: "VOID_UI_WAVE4_EARN_READONLY_V1",
    generated_at: generatedAt,
    read_only: true,
    network_name: "Mainnet-0",
    node: {
      label: "Local node",
      role: "local",
    },
    account: {
      selected: true,
      id: account,
      label: account,
    },
    earning: {
      source_available: true,
      status: "manual_only",
      status_label: "Manual only",
      enabled: true,
      manual_only: true,
      automatic_background: false,
      safe_mode: true,
      policy: "Useful, verifiable work only",
      approved_task_classes: [
        {
          task_class: "publish",
          label: "Publish data",
        },
        {
          task_class: "verify",
          label: "Verify data",
        },
        {
          task_class: "redundancy",
          label: "Check redundancy",
        },
      ],
      jobs_last_hour: 2,
      max_jobs_per_hour: 10,
      summary:
        "Earning is configured, but background execution is disabled. This Wave 4 view does not run work.",
      available_work: {
        available: true,
        task_class: "verify",
        task_label: "Verify data",
        reason: "A stale object is available for verification.",
        difficulty: "medium",
        network_need_score: 0.75,
        dataset_selected: true,
        execution_available: false,
      },
    },
    accounting: {
      legacy_wc: {
        available: true,
        earned: 12,
        earned_display: "12",
        redeemed: 3,
        redeemed_display: "3",
        redeemable: 9,
        redeemable_display: "9",
        debited: 0,
        debited_display: "0",
        spendable_claimed: false,
        redemption_action_available: false,
      },
      production_wc: {
        available: true,
        balance: 1.5,
        display: "1.5",
        entries: 2,
        ledger_version: "v1",
        spendable: false,
        redeemable: false,
        transferable: false,
        included_in_legacy_balance: false,
      },
      rewards_last_hour: {
        total: 4.5,
        total_display: "4.5",
        publish: 2,
        verify: 1.5,
        redundancy: 1,
      },
      last_credit: {
        available: true,
        amount: 1.5,
        amount_display: "1.5",
        task_class: "verify",
        task_label: "Verify data",
        reason: "Verified receipt credit.",
        recorded_at: "2026-09-29T11:59:00.000Z",
      },
    },
    recent_jobs: {
      available: true,
      count: 1,
      limit: 5,
      items: [
        {
          reference: "job-1",
          short_reference: "job-1",
          receipt_reference: "receipt-1",
          short_receipt_reference: "receipt-1",
          task_class: "verify",
          task_label: "Verify data",
          status: "completed",
          status_label: "Completed",
          result_label: "Verified",
          recorded_at: "2026-09-29T11:58:00.000Z",
          reward_wc: 1.5,
          reward_display: "1.5",
          dataset_selected: true,
          safe_mode: true,
        },
      ],
    },
    verification_receipts: {
      available: true,
      count: 1,
      limit: 5,
      items: [
        {
          reference: "receipt-1",
          short_reference: "receipt-1",
          job_reference: "job-1",
          short_job_reference: "job-1",
          task_class: "verify",
          task_label: "Verify data",
          status: "completed",
          status_label: "Completed",
          result_label: "Verified",
          recorded_at: "2026-09-29T11:58:30.000Z",
          reward_wc: 1.5,
          reward_display: "1.5",
          bytes: 1024,
          bytes_display: "1,024",
        },
      ],
    },
    datanet: {
      source_available: true,
      status: "available",
      receipt_store_records: 10,
      account_wc_events: 2,
      useful_work_policy: "Useful, verifiable work only",
      mutation: false,
    },
    sources: {
      runner_status: {
        route: "/wc/runner/status",
        ok: true,
        status: 200,
      },
      reward_stats: {
        route: "/wc/reward-stats",
        ok: true,
        status: 200,
      },
      redeemable: {
        route: "/wc/redeemable",
        ok: true,
        status: 200,
      },
      production_wc: {
        route: "/wc/production/balance",
        ok: true,
        status: 200,
      },
      jobs: {
        route: "/jobs",
        ok: true,
        status: 200,
      },
      receipts: {
        route: "/receipts",
        ok: true,
        status: 200,
      },
      datanet_wc: {
        route: "/__void/participant/datanet-wc/status",
        ok: true,
        status: 200,
      },
    },
    sanitization: {
      raw_source_bodies: false,
      absolute_paths: false,
      wallet_addresses: false,
      redeemed_event_wallets: false,
      job_inputs: false,
      job_meta: false,
      receipt_roots: false,
      receipt_leaves: false,
      receipt_payloads: false,
    },
    boundaries: {
      job_execution: false,
      job_submission: false,
      reward_award: false,
      runner_activation: false,
      runner_tick: false,
      runner_config: false,
      wc_redeem: false,
      wc_send: false,
      wc_to_void: false,
      ledger_write: false,
      browser_wallet_connection: false,
      validator_mutation: false,
      operator_mutation: false,
      money_movement: false,
    },
  };
}
