#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$ROOT"

G=".gitignore"
MARKER_BEGIN="# === ops backup churn (autogenerated) ==="
MARKER_END="# === /ops backup churn ==="

# patterns to ignore (NO deletions; this just prevents accidental adds)
PATTERNS=(
"ops/**/*.bak.*"
"ops/**/*.bak"
"ops/**/*~"
"ops/**/__pycache__/"
"ops/**/.pytest_cache/"
)

ensure_block() {
  if [ ! -f "$G" ]; then
    : > "$G"
  fi

  if grep -qF "$MARKER_BEGIN" "$G"; then
    return 0
  fi

  {
    echo
    echo "$MARKER_BEGIN"
    for p in "${PATTERNS[@]}"; do
      echo "$p"
    done
    echo "$MARKER_END"
  } >> "$G"
}

ensure_patterns_present() {
  # If the marker exists, ensure each pattern exists inside it (idempotent append before END).
  if ! grep -qF "$MARKER_BEGIN" "$G"; then
    ensure_block
    return 0
  fi

  tmp="$(mktemp)"
  awk -v begin="$MARKER_BEGIN" -v end="$MARKER_END" '
    {print}
  ' "$G" > "$tmp"

  for p in "${PATTERNS[@]}"; do
    if ! grep -qF "$p" "$G"; then
      # insert before MARKER_END
      awk -v end="$MARKER_END" -v line="$p" '
        $0==end {print line}
        {print}
      ' "$tmp" > "$tmp.2"
      mv "$tmp.2" "$tmp"
    fi
  done

  mv "$tmp" "$G"
}

echo "=== [gitignore ops backups] repo=$ROOT ==="
ensure_patterns_present
echo "[done] updated $G (idempotent)"
