#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$ROOT"

PATCH_ID="void-pillars-agecheck-v1"
BEGIN="# === ${PATCH_ID} BEGIN (autogenerated) ==="
END="# === ${PATCH_ID} END ==="

BLOCK="$(cat <<'EOF'
# === void-pillars-agecheck-v1 BEGIN (autogenerated) ===
# Gate: global pillars textfile exporter must be fresh (Prom-based; tiny query, no /metrics spam).
# Auto-heal (non-interactive): if stale, try a oneshot exporter run via sudo -n; otherwise fail with instructions.
if [ -x ./ops/void-pillars-health-age-check.sh ]; then
  export PROM="${PROM:-http://127.0.0.1:9090}"
  export MAX_AGE="${VOID_PILLARS_MAX_AGE:-180}"

  if ! ./ops/void-pillars-health-age-check.sh; then
    echo "[pillars-age] stale; attempting one-shot exporter run (sudo -n) ..."
    if sudo -n systemctl start void-pillars-health-exporter-v2.service 2>/dev/null; then
      sleep 2
      ./ops/void-pillars-health-age-check.sh
    else
      echo "[FAIL] pillars exporter stale and could not auto-run without sudo password."
      echo "       Run: sudo systemctl start void-pillars-health-exporter-v2.service"
      echo "       Then: ./ops/void-pillars-health-age-check.sh"
      exit 2
    fi
  fi
else
  echo "[WARN] missing ./ops/void-pillars-health-age-check.sh (skipping freshness gate)"
fi
# === void-pillars-agecheck-v1 END ===
EOF
)"

patch_one() {
  local f="$1"
  if [ ! -f "$f" ]; then
    echo "[skip] not found: $f"
    return 0
  fi

  if grep -qF "$BEGIN" "$f"; then
    echo "[ok] already patched: $f"
    return 0
  fi

  local ts
  ts="$(date +%Y%m%d-%H%M%S)"
  cp -a "$f" "$f.bak.$ts"
  echo "[backup] $f -> $f.bak.$ts"

  # Insert right after the first 'set -euo pipefail' line (or after shebang if not found).
  awk -v begin="$BEGIN" -v end="$END" -v block="$BLOCK" '
    BEGIN { inserted=0 }
    {
      print
      if (!inserted && $0 ~ /^set -euo pipefail$/) {
        print ""
        print block
        print ""
        inserted=1
      }
    }
    END {
      if (!inserted) {
        # fallback: append at end
        print ""
        print block
        print ""
      }
    }
  ' "$f" > "$f.tmp"
  mv "$f.tmp" "$f"
  chmod +x "$f"
  echo "[done] patched: $f"
}

echo "=== [patch] pillars preflight runners ==="
patch_one "ops/void-pillars-preflight.sh"
patch_one "ops/void-mainnet-pillars-preflight.sh"

echo "=== [sanity] bash -n ==="
bash -n ops/void-pillars-preflight.sh
bash -n ops/void-mainnet-pillars-preflight.sh

echo "[ok] patch complete"
