#!/usr/bin/env bash

# [void-root-autodetect]
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="${REPO_ROOT:-$DEFAULT_ROOT}"
ROOT="${ROOT:-$REPO_ROOT}"

#!/usr/bin/env bash
set -euo pipefail

### [auto] refresh mainnet manifest pillar gauges (textfile) ###
sudo -n ./ops/void-mainnet-core-manifest-exporter-v2.sh >/dev/null 2>&1 || true
sleep 6

### [auto] end refresh ###


# === void-pillars-agecheck-v1 BEGIN (autogenerated) ===
# Gate: global pillars textfile exporter must be fresh (Prom-based; tiny query, no /metrics spam).
# Auto-heal (non-interactive): if stale, try a oneshot exporter run via sudo -n; otherwise fail with instructions.
if [ -x ./ops/void-pillars-health-age-check.sh ]; then
  export PROM="${PROM:-http://127.0.0.1:9090}"
  export MAX_AGE="${VOID_PILLARS_MAX_AGE:-180}"

  if ! ./ops/void-pillars-health-age-check.sh; then
    echo "[pillars-age] stale; attempting one-shot exporter run (sudo -n) ..."
    if sudo -n systemctl start void-pillars-health-exporter-v2.service 2>/dev/null; then
      sleep 2
      ./ops/void-pillars-health-age-check.sh
    else
      echo "[FAIL] pillars exporter stale and could not auto-run without sudo password."
      echo "       Run: sudo systemctl start void-pillars-health-exporter-v2.service"
      echo "       Then: ./ops/void-pillars-health-age-check.sh"
      exit 2
    fi
  fi
else
  echo "[WARN] missing ./ops/void-pillars-health-age-check.sh (skipping freshness gate)"
fi
# === void-pillars-agecheck-v1 END ===


ROOT="${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PROM_URL="${PROM_URL:-http://127.0.0.1:9090}"

cd "$ROOT"

echo "[pillars-preflight] repo=${ROOT}"
echo

echo "[pillars-preflight] === step: safeboot health-all ==="
./ops/void-safeboot-health-all.sh
echo

echo "[pillars-preflight] === step: devnet health-all ==="
./ops/void-devnet-health-all.sh
echo

echo "[pillars-preflight] === step: mainnet-core health-all ==="
./ops/void-mainnet-core-health-all.sh
echo

echo "[pillars-preflight] === step: mainnet-lastmile health-all ==="
./ops/void-mainnet-lastmile-health-all.sh
echo

echo "[pillars-preflight] === step: pillars health-all ==="
./ops/void-mainnet-pillars-health-all.sh
echo

q() {
  local expr="$1"
  curl -fsS "${PROM_URL}/api/v1/query" \
    --data-urlencode "query=${expr}" \
    | jq -r '.data.result[0].value[1] // "NaN"' 2>/dev/null
}

echo "[pillars-preflight] === step: pillars+validators+RewardEngine+WorkCredits econ 5m health ==="
combo="$(q 'void:mainnet_pillars_with_validators_rewardengine_econ_workcredits_plan:health:last_5m')"
echo "  void:mainnet_pillars_with_validators_rewardengine_econ_workcredits_plan:health:last_5m = ${combo}"
echo

if [ "${combo}" != "1" ]; then
  echo "[pillars-preflight] ERROR: combined mainnet pillars+validators+RewardEngine+WorkCredits econ 5m health != 1 (=${combo})"
  echo "[pillars-preflight] HINT: run ./ops/void-mainnet-pillars-with-rewardengine-econ-workcredits-health.sh for a detailed breakdown."
  exit 1
fi

echo "[pillars-preflight] RESULT: OK (safeboot + devnet + mainnet-core + mainnet-lastmile + pillars + econ/WorkCredits all healthy)"
