#!/usr/bin/env bash
set -euo pipefail

# === void-pillars-agecheck-v1 BEGIN (autogenerated) ===
# Gate: global pillars textfile exporter must be fresh (Prom-based; tiny query, no /metrics spam).
# Auto-heal (non-interactive): if stale, try a oneshot exporter run via sudo -n; otherwise fail with instructions.
if [ -x ./ops/void-pillars-health-age-check.sh ]; then
  export PROM="${PROM:-http://127.0.0.1:9090}"
  export MAX_AGE="${VOID_PILLARS_MAX_AGE:-180}"

  if ! ./ops/void-pillars-health-age-check.sh; then
    echo "[pillars-age] stale; attempting one-shot exporter run (sudo -n) ..."
    if sudo -n systemctl start void-pillars-health-exporter-v2.service 2>/dev/null; then
      sleep 2
      ./ops/void-pillars-health-age-check.sh
    else
      echo "[FAIL] pillars exporter stale and could not auto-run without sudo password."
      echo "       Run: sudo systemctl start void-pillars-health-exporter-v2.service"
      echo "       Then: ./ops/void-pillars-health-age-check.sh"
      exit 2
    fi
  fi
else
  echo "[WARN] missing ./ops/void-pillars-health-age-check.sh (skipping freshness gate)"
fi
# === void-pillars-agecheck-v1 END ===


REPO="${REPO:-$(pwd)}"
echo "[pillars-preflight] repo=$REPO"

run_step() {
  local name="$1"
  shift
  echo
  echo "[pillars-preflight] === step: $name ==="
  "$@"
}

run_step "safeboot health-all"          ./ops/void-safeboot-health-all.sh
run_step "devnet health-all"            ./ops/void-devnet-health-all.sh
run_step "mainnet-core health-all"      ./ops/void-mainnet-core-health-all.sh
run_step "mainnet-lastmile health-all"  ./ops/void-mainnet-lastmile-health.sh
run_step "pillars health-all"           ./ops/void-pillars-health-all.sh

echo
echo "[pillars-preflight] RESULT: OK (safeboot + devnet + mainnet-core + mainnet-lastmile + pillars all healthy)"
