[Service]
Environment=VOID_SAFEBOOT=1
Environment=HEADER3_HARDLOCK_DISABLE=1
Environment=VOID_SAFEBOOT_ALLOW=/__void/about2,/__void/ready,/__void/ready.prom,/__void/ready.json,/metrics/void,/blocks/latest/number,/blocks/latest/number.json,/blocks/latest/number2.json,/head.txt,/mempool/submit,/mempool/node/ingest-now,/proposer/queue/size,/proposer/auto/start,/proposer/pump.v1b
